### ISSUE TITLE
Server borks if it is started without password

### ISSUE THREAD

**Issue by gerroon** [kopia/kopia#1137]
The server crashes some seconds after started and if the user browses the web address. I can access the web ui, but only for couple seconds really.

Debian Testing X64

```
kopia server start --tls-cert-file ~/my.cert --tls-key-file ~/kopia.key --without-password --insecure --address 0.0.0.0:51515

SERVER ADDRESS: https://[::]:51515
Open the address above in a web browser to use the UI.
2021/06/13 14:43:09 http: TLS handshake error from 192.168.1.100:55057: remote error: tls: unknown certificate
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xc65f9c]

goroutine 504 [running]:
github.com/kopia/kopia/internal/server.(*Server).authenticateGRPCSession(0xc0000c0160, 0x18b8008, 0xc004ea5890, 0x18caf38, 0xc0002d9440, 0xed301, 0x203c300)
        /home/runner/work/kopia/kopia/internal/server/grpc_session.go:60 +0x25c
github.com/kopia/kopia/internal/server.(*Server).Session(0xc0000c0160, 0x18c34d8, 0xc004cb2bd0, 0x0, 0x0)
        /home/runner/work/kopia/kopia/internal/server/grpc_session.go:79 +0x126
github.com/kopia/kopia/internal/grpcapi._KopiaRepository_Session_Handler(0x13268c0, 0xc0000c0160, 0x18bf210, 0xc004c1a600, 0x2039d88, 0xc000757c20)
        /home/runner/work/kopia/kopia/internal/grpcapi/repository_server_grpc.pb.go:94 +0xad
google.golang.org/grpc.(*Server).processStreamingRPC(0xc0006c2000, 0x18c4618, 0xc004eac510, 0xc000757c20, 0xc0004090b0, 0x1feef00, 0x0, 0x0, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.1/server.go:1464 +0xcd8
google.golang.org/grpc.(*Server).handleStream(0xc0006c2000, 0x18c4618, 0xc004eac510, 0xc000757c20, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.1/server.go:1544 +0xca5
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc004cdee60, 0xc0006c2000, 0x18c4618, 0xc004eac510, 0xc000757c20)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.1/server.go:878 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.37.1/server.go:876 +0x1fd

```

**Comment by jkowalski** [comment]
can you describe exactly what the client is doing at this point? visiting the UI or connecting to the repository server?

**Comment by gerroon** [comment]
Just visiting the UI and trying to load "all repositories"

**Comment by gerroon** [comment]
Ok, I still have the issue with 0.8.4 and this is really tied to the `--without-password --insecure ` combo because I get the crash when I fire up the regular kopia-ui from another computer. Removing those stops the crashes but I cant seem to be able to access the web ui in the current version.

**Comment by jkowalski** [comment]
ok, that makes sense, the crash is when a GRPC client from another computer connects.

**Comment by wechsler42** [comment]
Hi there,
I just stumbled over the same issue with Kopia 0.10.7 . Do you know any workaround with still leaving the combo "--without-password --insecure" in place until the bug is fixed?

**Comment by gerroon** [comment]
I was not  able to solve it, I do not even understand how the server supposed to be in this respect. The documents were not making it clear to be honest.

**Comment by wechsler42** [comment]
I also tried to tweak and to understand, also without any results. In fact, I run out of ideas and I hope @jkowalski  could bring some light into this.
