### ISSUE TITLE
runtime: VirtualAlloc of 67108864 bytes failed with errno=1455

### ISSUE THREAD

**Issue by hrez** [kopia/kopia#1216]
Hi,
When I start kopia server it attempts to snapshot one of the local sources and crashes with "out of memory" error.
Task manager shows a jump of few gigabytes( ~6Gb) in memory usage which then is released after the crash. 
The error message below says 67Mb but it consumes gigabytes.
If I rename local source dir the server runs fine. So it's only the snapshot that creates this issue.
The source dir isn't particularly big - ~1.7Gb, ~45k files.
It's an old snapshot setup so it was working before but perhaps on a smaller dataset.

I don't see anything usable in logs. How do I approach in fixing it?

```
> kopia server start --insecure
Server will allow connections from users whose accounts are stored in the repository.
User accounts can be added using 'kopia server user add'.
SERVER ADDRESS: http://127.0.0.1:51515
Open the address above in a web browser to use the UI.
runtime: VirtualAlloc of 67108864 bytes failed with errno=1455
fatal error: out of memory

runtime stack:
runtime.throw(0x1171605, 0xd)
        C:/hostedtoolcache/windows/go/1.16.3/x64/src/runtime/panic.go:1117 +0x79
runtime.sysUsed(0xc25dc10000, 0x4000000)
        C:/hostedtoolcache/windows/go/1.16.3/x64/src/runtime/mem_windows.go:83 +0x22e
runtime.(*mheap).allocSpan(0x1e23b40, 0x2000, 0x100, 0x1abf80c6688)
        C:/hostedtoolcache/windows/go/1.16.3/x64/src/runtime/mheap.go:1271 +0x3b1
runtime.(*mheap).alloc.func1()
        C:/hostedtoolcache/windows/go/1.16.3/x64/src/runtime/mheap.go:910 +0x5f
runtime.systemstack(0x0)
        C:/hostedtoolcache/windows/go/1.16.3/x64/src/runtime/asm_amd64.s:379 +0x6b
runtime.mstart()
        C:/hostedtoolcache/windows/go/1.16.3/x64/src/runtime/proc.go:1246

goroutine 248359 [running]:
runtime.systemstack_switch()
        C:/hostedtoolcache/windows/go/1.16.3/x64/src/runtime/asm_amd64.s:339 fp=0xc00130d398 sp=0xc00130d390 pc=0x33d1e0
runtime.(*mheap).alloc(0x1e23b40, 0x2000, 0x1abf8100101, 0x0)
        C:/hostedtoolcache/windows/go/1.16.3/x64/src/runtime/mheap.go:904 +0x88 fp=0xc00130d3e8 sp=0xc00130d398 pc=0x2f8fa8
runtime.(*mcache).allocLarge(0x1abf1aa1348, 0x4000000, 0x101, 0x10da240)
        C:/hostedtoolcache/windows/go/1.16.3/x64/src/runtime/mcache.go:224 +0x9e fp=0xc00130d440 sp=0xc00130d3e8 pc=0x2e90be
<rest is skipped>

```

windows 10, x64
kopia 0.8.4, I also tried the latest master branch build

**Comment by hrez** [comment]
> Can you try 0.9.0-rc4 - it has gotten some memory usage improvements?

Looks like that helped. Thank you.
