### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by Birne94** [kopia/kopia#176]
When creating a snapshot of a data directory today, kopia failed with a segmentation fault:

```
~$ kopia snapshot create /var/data/
11:59:20.142 [kopia/cli] processing upload 'n1f09d82dfeb1faa4f86080ef179983ae' 0 B of 173.8 KB (0%)
11:59:20.453 [kopia/cli] completed upload 'n1f09d82dfeb1faa4f86080ef179983ae' 173.8 KB
11:59:22.130 [kopia/cli] snapshotting user@host:/var/data
11:59:22.144 [kopia/cli] processing upload 'q7e4befa5a4b88243ddf983177d7eac6c' 0 B of 6 KB (0%)
11:59:23.056 [kopia/cli] completed upload 'q7e4befa5a4b88243ddf983177d7eac6c' 6 KB
11:59:23.056 [kopia/cli] processing upload 'n4b66f86549dd18b2511a542e074abe83' 0 B of 1.9 KB (0%)
11:59:23.489 [kopia/cli] completed upload 'n4b66f86549dd18b2511a542e074abe83' 1.9 KB
11:59:23.491 [kopia/cli] uploading user@host:/var/data using 1 previous manifests
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x87ffd7]

goroutine 96 [running]:
github.com/kopia/kopia/fs/localfs.entryFromChildFileInfo(0x0, 0x0, 0xc004644a74, 0x9, 0xf12700, 0xc0044ee5d0, 0x7, 0xc00009eb40)
        /home/travis/gopath/src/github.com/kopia/kopia/fs/localfs/local_fs.go:277 +0x37
github.com/kopia/kopia/fs/localfs.(*filesystemDirectory).Readdir.func2(0xc004644ab0, 0xc0000a3200, 0xc004644a74, 0x9, 0xc0000a3260)
        /home/travis/gopath/src/github.com/kopia/kopia/fs/localfs/local_fs.go:185 +0x1a8
created by github.com/kopia/kopia/fs/localfs.(*filesystemDirectory).Readdir
        /home/travis/gopath/src/github.com/kopia/kopia/fs/localfs/local_fs.go:175 +0x2ba
```

The directory in question is a data directory including persistent data from redis, influxdb, mariadb, postgres and some other containers. After investigating for a little bit, **missing directory permissions (+x in particular) seem to be the cause for this crash.**

`sudo chmod -R u=rwx,go=rx  /var/data` fixes the error for now, but I think kopia should not crash at this point.

**Comment by redgoat650** [comment]
Thanks @Birne94 -This was recently caught and fixed by #173. Closing issue for now
