### ISSUE TITLE
panic: sync: WaitGroup is reused before previous Wait has returned

### ISSUE THREAD

**Issue by gp-Airee** [kopia/kopia#1778]
while taking a fresh snapshot of a large directory to a Kopia server...

```
 / 16 hashing, 142197 hashed (71.2 GB), 0 cached (0 B), uploaded 71.1 GB, estimated 277.6 GB (25.6%) 10h29m45s
```

```
leftpanic: sync: WaitGroup is reused before previous Wait has returned

goroutine 82 [running]:
sync.(*WaitGroup).Wait(0x0)
        /opt/hostedtoolcache/go/1.17.3/x64/src/sync/waitgroup.go:132 +0xa5
golang.org/x/sync/errgroup.(*Group).Wait(0xc004a60058)
        /home/runner/go/pkg/mod/golang.org/x/sync@v0.0.0-20210220032951-036812b2e83c/errgroup/errgroup.go:40 +0x27
github.com/kopia/kopia/repo.(*grpcRepositoryClient).Flush(0xc004a60000, {0x18045c8, 0xc000758fc0})
        /home/runner/work/kopia/kopia/repo/grpc_repository_client.go:384 +0x31
github.com/kopia/kopia/snapshot/snapshotfs.(*Uploader).checkpointRoot(0xc004b4db80, {0x18045c8, 0xc000758fc0},
0x0, 0xc0000dc300)
        /home/runner/work/kopia/kopia/snapshot/snapshotfs/upload.go:432 +0x32b
github.com/kopia/kopia/snapshot/snapshotfs.(*Uploader).periodicallyCheckpoint.func1()
        /home/runner/work/kopia/kopia/snapshot/snapshotfs/upload.go:452 +0xec
created by github.com/kopia/kopia/snapshot/snapshotfs.(*Uploader).periodicallyCheckpoint
        /home/runner/work/kopia/kopia/snapshot/snapshotfs/upload.go:445 +0x130
```

**Comment by jkowalski** [comment]
that's a great catch!

**Comment by jkowalski** [comment]
I tried to repro this bug to prove the fix but it's very difficult, it must be a super-tight race condition. Will keep looking.

**Comment by celogeek** [comment]
I use a kopia server and run kopia snap in parallel on different machines.
this happen a lot actually.
I have to restart the whole process and sometimes it is huge.
I try to add a checkpoint to see if that resume faster.

**Comment by celogeek** [comment]
Can we backup a directory while modifying it at the same times ???
It fail something like 10 times now to backup, and resume looks like it try to do it again from the beginning.

**Comment by celogeek** [comment]
checkpoint doesn't work too, but it may be related to a network issue.

I've test the master branch, and now it works without this issue. I'm testing gigabytes of backup right now.

**Comment by cebtenzzre** [comment]
Still present on Kopia v0.22.3 (Windows 11, client connected to a remote repository server via gRPC).

This occurred during the second full snapshot of a large source (~70 GB total, ~5.3 GB hashed at time of panic). There were 7 pre-existing fatal errors (file read errors on the source volume, e.g. `hiberfil.sys` "Access Denied") at the time of the crash -- the race may be easier to trigger when the uploader is already in a partially-failed state.

Note that `x/sync` is now at `v0.18.0` (vs `v0.0.0-2021...` in the original report).

```
 \ 7 hashing, 1448 hashed (5.3 GB), 142442 cached (65.7 GB), uploaded 4.8 GB (7
fatal errors), estimating...panic: sync: WaitGroup is reused before previous Wait
has returned

goroutine 80 [running]:
sync.(*WaitGroup).Wait(0xc0065763c8)
	sync/waitgroup.go:208 +0xf4
golang.org/x/sync/errgroup.(*Group).Wait(0xc0065763c0)
	golang.org/x/sync@v0.18.0/errgroup/errgroup.go:56 +0x1e
github.com/kopia/kopia/repo.(*grpcRepositoryClient).Flush(0xc00011a840, {0x7ff6cd0a9418,
0xc0072e4180})
	github.com/kopia/kopia/repo/grpc_repository_client.go:514 +0x2a
github.com/kopia/kopia/snapshot/upload.(*Uploader).checkpointRoot(0xc00668aa50, {0x7ff6cd0a9418,
0xc0067fc9f0}, 0xc0067a26f0, 0xc0067903c0)
	github.com/kopia/kopia/snapshot/upload/upload.go:549 +0x43a
github.com/kopia/kopia/snapshot/upload.(*Uploader).periodicallyCheckpoint.func1()
	github.com/kopia/kopia/snapshot/upload/upload.go:569 +0xcf
created by github.com/kopia/kopia/snapshot/upload.(*Uploader).periodicallyCheckpoint in goroutine
1
	github.com/kopia/kopia/snapshot/upload/upload.go:562 +0xf8
```
