### ISSUE TITLE
panic: runtime error: makeslice: len out of range

### ISSUE THREAD

**Issue by cirrusflyer** [kopia/kopia#2507]
Running 0.12.1 x64 Linux version on Synology NAS.  Has been working fine, but recently started seeing this error:

panic: runtime error: makeslice: len out of range

And jobs don't complete.

**Comment by ajctrl** [comment]
e2, docker:latest (2022-10) same here
Server will allow connections from users whose accounts are stored in the repository.
User accounts can be added using 'kopia server user add'.

panic: runtime error: makeslice: len out of range

goroutine 40 [running]:
github.com/kopia/kopia/internal/epoch.(*Manager).getCompleteIndexSetForCommittedState(0xc0003e68c0, {0x1afe5c8, 0xc00002f9e0}, {0x0, 0xc00019e4e0, {0xc000404248, 0x1, 0x1}, 0xc0002a3020, 0xc0002a2fc0, ...}, ...)
	/home/runner/work/kopia/kopia/internal/epoch/epoch_manager.go:828 +0x44a
github.com/kopia/kopia/internal/epoch.(*Manager).GetCompleteIndexSet(0xc0003e68c0, {0x1afe5c8, 0xc00002f9e0}, 0x1?)
	/home/runner/work/kopia/kopia/internal/epoch/epoch_manager.go:674 +0x1d5
github.com/kopia/kopia/repo/content.(*indexBlobManagerV1).listActiveIndexBlobs(0xc0004c02d0, {0x1afe5c8?, 0xc00002f9e0?})
	/home/runner/work/kopia/kopia/repo/content/index_blob_manager_v1.go:30 +0x69
github.com/kopia/kopia/repo/content.(*SharedManager).loadPackIndexesLocked(0xc0000001e0, {0x1afe5c8, 0xc00002f9e0})
	/home/runner/work/kopia/kopia/repo/content/committed_read_manager.go:207 +0x1ba
github.com/kopia/kopia/repo/content.NewSharedManager({0x1afe5c8?, 0xc00002f9e0}, {0x1b04618?, 0xc0002a2630}, 0xc00010e270, 0xc000381080, 0xc0005c4400?)
	/home/runner/work/kopia/kopia/repo/content/committed_read_manager.go:621 +0x609
github.com/kopia/kopia/repo.openWithConfig({0x1afe5c8, 0xc00002f9e0}, {0x1b04618, 0xc0002a2630}, 0xc000341500, {0xc0003a4f80, 0x40}, 0xc000233dd0, 0xc00040c960?, {0xc000044042, ...})
	/home/runner/work/kopia/kopia/repo/open.go:329 +0x792
github.com/kopia/kopia/repo.openDirect({0x1afe5c8, 0xc00002f9e0}, {0xc000044042, 0x1d}, 0xc000341500, {0xc0003a4f80, 0x40}, 0xc00019bdd0)
	/home/runner/work/kopia/kopia/repo/open.go:183 +0x227
github.com/kopia/kopia/repo.Open({0x1afe520?, 0xc0005c9900?}, {0xc000044042, 0x1d}, {0xc0003a4f80, 0x40}, 0xc00018edd0)
	/home/runner/work/kopia/kopia/repo/open.go:113 +0x345
github.com/kopia/kopia/cli.(*App).openRepository(0xc0005d2500, {0x1afe520, 0xc0005c9900}, 0x0)
	/home/runner/work/kopia/kopia/cli/config.go:62 +0x18b
github.com/kopia/kopia/cli.(*commandServerStart).initRepositoryPossiblyAsync.func1({0x1afe520?, 0xc0005c9900?})
	/home/runner/work/kopia/kopia/cli/command_server_start.go:156 +0x42
github.com/kopia/kopia/internal/server.(*Server).InitRepositoryAsync.func1({0x1afe5c8, 0xc00002f8c0}, {0x1afe8d8, 0xc00067cb60})
	/home/runner/work/kopia/kopia/internal/server/server.go:911 +0x1b9
github.com/kopia/kopia/internal/uitask.(*Manager).Run(0xc00002f770, {0x1afe5c8, 0xc00002f590}, {0x144e358, 0xa}, {0x1446f7a, 0x4}, 0xc00002f860)
	/home/runner/work/kopia/kopia/internal/uitask/uitask_manager.go:63 +0x1c9
created by github.com/kopia/kopia/internal/server.(*Server).InitRepositoryAsync
	/home/runner/work/kopia/kopia/internal/server/server.go:895 +0x22a

**Comment by cirrusflyer** [comment]
I had this occur on two servers, and now just happened on my third.  Is it related to e2 or Kopia?  Anyone know more?

**Comment by stefangweichinger** [comment]
Is this https://kopia.discourse.group/t/seeing-kopia-connect-crash-having-large-number-of-epochs/2189 the same?

**Comment by stefangweichinger** [comment]
Could someone have a look? This breaks backups AFAIK.
