### ISSUE TITLE
Server Segmentation Fault running v0.12.0

### ISSUE THREAD

**Issue by barnumbirr** [kopia/kopia#2516]
Hi,

when running [kopia v0.12.0 on a x86 QNAP serve](https://www.qnapclub.eu/en/qpkg/1126)r, kopia sometimes segfaults as follows:

```
# kopia server start --tls-cert-file /opt/Kopia/kopia.cert --tls-key-file /opt/Kopia/kopia.key --address 0.0.0.0:51515 --without-password --insecure
SERVER ADDRESS: https://[::]:51515
Open the address above in a web browser to use the UI.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xcce7aa]

goroutine 167 [running]:
github.com/kopia/kopia/internal/server.(*Server).authenticateGRPCSession(0xc000643520, {0x1ba2ff8, 0xc000698990}, {0x7f1ab8f508b8, 0xc0004ee120})
        /home/runner/work/kopia/kopia/internal/server/grpc_session.go:63 +0x1aa
github.com/kopia/kopia/internal/server.(*Server).Session(0xc000643520, {0x1ba7c60, 0xc00007da00})
        /home/runner/work/kopia/kopia/internal/server/grpc_session.go:85 +0x153
github.com/kopia/kopia/internal/grpcapi._KopiaRepository_Session_Handler({0x14e8440?, 0xc000643520}, {0x1ba62a8?, 0xc00067e680})
        /home/runner/work/kopia/kopia/internal/grpcapi/repository_server_grpc.pb.go:98 +0x9f
google.golang.org/grpc.(*Server).processStreamingRPC(0xc006f16b40, {0x1ba86b8, 0xc006b50510}, 0xc006b53320, 0xc006f5e7b0, 0x2491a20, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.49.0/server.go:1564 +0xf46
google.golang.org/grpc.(*Server).handleStream(0xc006f16b40, {0x1ba86b8, 0xc006b50510}, 0xc006b53320, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.49.0/server.go:1646 +0x9d6
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.49.0/server.go:938 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.49.0/server.go:936 +0x28a
```

It seems removing the `--without-password --insecure` arguments "fix" the issue and the server can be restarted with any further issues.

Cheers.

**Comment by jkowalski** [comment]
Yes, `--without-password` is causing this. We should prevent this combination of flags along with GRPC.

**Comment by gdbinit** [comment]
I was testing things and of course I hit this bug and found this issue.
The bug root cause is a nil pointer in this method when trying to validate authentication for a gRPC session:
```go
func (s *Server) authenticateGRPCSession(ctx context.Context, rep repo.Repository) (string, error) {
    md, ok := metadata.FromIncomingContext(ctx)
    if !ok {
        return "", status.Errorf(codes.PermissionDenied, "metadata not found in context")
    }
    if u, h, p := md.Get("kopia-username"), md.Get("kopia-hostname"), md.Get("kopia-password"); len(u) == 1 && len(p) == 1 && len(h) == 1 {
        username := u[0] + "@" + h[0]
        password := p[0]
        // crashes here because s.authenticator is nil if --without-password --insecure is used
        if s.authenticator.IsValid(ctx, rep, username, password) {
            return username, nil
        }

        return "", status.Errorf(codes.PermissionDenied, "access denied for %v", username)
    }

    return "", status.Errorf(codes.PermissionDenied, "missing credentials")
}
```

I was looking at the best way to fix this and the more logical one would be to introduce a new authenticator that returns always `true` when using the `--without-password` option. But this enters in conflict with the current checks that just assume the `nil` value for the authenticator when using that option. This would require a more complex fix because of that and might be too early in the code path to call the authenticators (didn't verify this but have a feeling that might be the reason for the current code). The main problem seems to be a mixup in the authenticators between all the parts, UI and repositories via gRPC (or maybe due to support legacy issues). The repository users are always authenticated to the UI which seems a bit weird (or maybe not).

Anyway, the easiest fix is to just introduce a nil pointer check in `authenticateGRPCSession()`. Since this accepts any username this might lead to problems ahead, which are probably irrelevant since this mode should be only used for testing and users aren't going to inject random usernames into the gRPC session manually (unless they are fuzzing or something).

```go
func (s *Server) authenticateGRPCSession(ctx context.Context, rep repo.Repository) (string, error) {
    md, ok := metadata.FromIncomingContext(ctx)
    if !ok {
        return "", status.Errorf(codes.PermissionDenied, "metadata not found in context")
    }
    if u, h, p := md.Get("kopia-username"), md.Get("kopia-hostname"), md.Get("kopia-password"); len(u) == 1 && len(p) == 1 && len(h) == 1 {
        username := u[0] + "@" + h[0]
        password := p[0]
        // verify if the authenticator is nil, which happens when --without-password is used to start the server
        // this means that any user can call the gRPC server
        if s.authenticator == nil {
            return username, nil
        }
        if s.authenticator.IsValid(ctx, rep, username, password) {
            return username, nil
        }

        return "", status.Errorf(codes.PermissionDenied, "access denied for %v", username)
    }

    return "", status.Errorf(codes.PermissionDenied, "missing credentials")
}
```

Does this makes sense or am I missing something? I can submit a PR if it does.
