### ISSUE TITLE
Snapshot create panic: counter cannot decrease value 

### ISSUE THREAD

**Issue by saviodsouza** [kopia/kopia#3342]
Hi

This appears to be a bug

Running kopia 14.1 linux amd64

```
| 0 hashing, 39 hashed (14.4 MB), 49306 cached (3.6 GB), uploaded 202 B, estimating...panic: counter cannot decrease in value

goroutine 207 [running]:
github.com/prometheus/client_golang/prometheus.(*counter).Add(0x2861800?, 0xc13b3c87c9228bad?)
	/home/runner/go/pkg/mod/github.com/prometheus/client_golang@v1.16.0/prometheus/counter.go:121 +0xe9
github.com/kopia/kopia/internal/metrics.(*Counter).Add(...)
	/home/runner/work/kopia/kopia/internal/metrics/metrics_counter.go:22
github.com/kopia/kopia/internal/metrics.(*Throughput).Observe(0xc0000a71f0?, 0x114?, 0xfffffffffffff8c9)
	/home/runner/work/kopia/kopia/internal/metrics/metrics_throughput.go:20 +0x8b
github.com/kopia/kopia/repo/content.(*SharedManager).decryptContentAndVerify(0xc000214180, {{0xc0a274aa28, 0x1, 0x1}, {{0xc005584000, 0x130, 0x10000}}}, {0x1de07c0, 0xc0a2752370}, 0xc0a274a840)
	/home/runner/work/kopia/kopia/repo/content/committed_read_manager.go:322 +0x79b
github.com/kopia/kopia/repo/content.(*SharedManager).getContentDataReadLocked(0xc000214180, {0x1dd7360, 0xc0053782d0}, 0x0, {0x1de07c0, 0xc0a2752370}, 0x1dd7360?)
	/home/runner/work/kopia/kopia/repo/content/content_manager_lock_free.go:121 +0x416
github.com/kopia/kopia/repo/content.(*WriteManager).getContentDataAndInfo(0xc000678420, {0x1dd7360, 0xc0053782d0}, {{0x9c, 0x9e, 0x48, 0x55, 0xcd, 0x6d, 0x22, ...}, ...}, ...)
	/home/runner/work/kopia/kopia/repo/content/content_manager.go:671 +0x138
github.com/kopia/kopia/repo/content.(*WriteManager).GetContent(0xc000678420, {0x1dd7360, 0xc0053782d0}, {{0x9c, 0x9e, 0x48, 0x55, 0xcd, 0x6d, 0x22, ...}, ...})
	/home/runner/work/kopia/kopia/repo/content/content_manager.go:858 +0x175
github.com/kopia/kopia/repo/object.newRawReader({0x1dd7360?, 0xc0053782d0?}, {0x1dd36b0?, 0xc000678420?}, {{{0x9c, 0x9e, 0x48, 0x55, 0xcd, 0x6d, ...}, ...}, ...}, ...)
	/home/runner/work/kopia/kopia/repo/object/object_reader.go:289 +0x142
github.com/kopia/kopia/repo/object.openAndAssertLength({0x1dd7360?, 0xc0053782d0?}, {0x1dd36b0?, 0xc000678420?}, {{{0x9c, 0x9e, 0x48, 0x55, 0xcd, 0x6d, ...}, ...}, ...}, ...)
	/home/runner/work/kopia/kopia/repo/object/object_reader.go:220 +0x2b7
github.com/kopia/kopia/repo/object.Open(...)
	/home/runner/work/kopia/kopia/repo/object/object_reader.go:17
github.com/kopia/kopia/repo.(*directRepository).OpenObject(0xc05d7b4f48?, {0x1dd7360?, 0xc0053782d0?}, {{{0x9c, 0x9e, 0x48, 0x55, 0xcd, 0x6d, 0x22, ...}, ...}, ...})
	/home/runner/work/kopia/kopia/repo/repository.go:195 +0x5b
github.com/kopia/kopia/snapshot/snapshotfs.(*repositoryDirectory).loadLocked(0xc0a2760150, {0x1dd7360?, 0xc0053782d0?})
	/home/runner/work/kopia/kopia/snapshot/snapshotfs/repofs.go:173 +0x96
github.com/kopia/kopia/snapshot/snapshotfs.(*repositoryDirectory).ensureDirEntriesLoaded(0xb4?, {0x1dd7360?, 0xc0053782d0?})
	/home/runner/work/kopia/kopia/snapshot/snapshotfs/repofs.go:158 +0xd4
github.com/kopia/kopia/snapshot/snapshotfs.(*repositoryDirectory).Child(0xc0a2760150, {0x1dd7360?, 0xc0053782d0?}, {0xc0a2764237, 0x9})
	/home/runner/work/kopia/kopia/snapshot/snapshotfs/repofs.go:124 +0x36
github.com/kopia/kopia/snapshot/snapshotfs.findCachedEntry({0x1dd7360, 0xc0053782d0}, {0xc0a2764300, 0x51}, {0x1ddfe38?, 0xc005145220}, {0xc0a27542a0?, 0x1, 0x418608?}, 0xc0050f7428)
	/home/runner/work/kopia/kopia/snapshot/snapshotfs/upload.go:702 +0x12a
github.com/kopia/kopia/snapshot/snapshotfs.(*Uploader).processSingle(0xc005462160, {0x1dd7360, 0xc0053782d0}, {0x1ddfe38?, 0xc005145220}, {0xc0a2764300, 0x51}, 0xc00044aa00?, 0xc0050f7428, {0xc0a27542a0, ...}, ...)
	/home/runner/work/kopia/kopia/snapshot/snapshotfs/upload.go:831 +0x172
github.com/kopia/kopia/snapshot/snapshotfs.(*Uploader).processDirectoryEntries.func1({0x1dd7360?, 0xc0053782d0}, {0x1ddfe38?, 0xc005145220})
	/home/runner/work/kopia/kopia/snapshot/snapshotfs/upload.go:789 +0x468
github.com/kopia/kopia/fs/ignorefs.(*ignoreDirectory).IterateEntries.func1({0x1dd7360, 0xc0053782d0}, {0x1ddfe38?, 0xc005145220?})
	/home/runner/work/kopia/kopia/fs/ignorefs/ignorefs.go:163 +0x68
github.com/kopia/kopia/fs/localfs.(*filesystemDirectory).IterateEntries(0xc010337d10, {0x1dd7360, 0xc0053782d0}, 0xc0a24818a0)
	/home/runner/work/kopia/kopia/fs/localfs/local_fs.go:174 +0x355
github.com/kopia/kopia/fs/ignorefs.(*ignoreDirectory).IterateEntries(0xc0a2760030, {0x1dd7360, 0xc0053782d0}, 0xc0a274c770)
	/home/runner/work/kopia/kopia/fs/ignorefs/ignorefs.go:161 +0xe9
github.com/kopia/kopia/snapshot/snapshotfs.(*Uploader).processDirectoryEntries(0xc005462160, {0x1dd7360, 0xc0053782d0}, 0xc0a27542b0, 0xc0a24c7300, {0xc0a272df80, 0x56}, {0xc0a24ffa90, 0x47}, {0x1de21c0, ...}, ...)
	/home/runner/work/kopia/kopia/snapshot/snapshotfs/upload.go:777 +0x1b0
github.com/kopia/kopia/snapshot/snapshotfs.(*Uploader).processChildren(0xc005462160, {0x1dd7360, 0xc0053782d0}, 0xc0a2589c80?, 0x1418960?, {0xc0a272df80, 0x56}, {0xc0a24ffa90, 0x47}, {0x1de21c0, ...}, ...)
	/home/runner/work/kopia/kopia/snapshot/snapshotfs/upload.go:653 +0x185
github.com/kopia/kopia/snapshot/snapshotfs.uploadDirInternal({0x1dd7360?, 0xc0053782d0?}, 0xc005462160, {0x1de21c0, 0xc0a2760030}, 0xc0050f7428, {0xc0a27542a0, 0x1, 0x1}, {0xc0a272df80, ...}, ...)
	/home/runner/work/kopia/kopia/snapshot/snapshotfs/upload.go:1148 +0xa87
github.com/kopia/kopia/snapshot/snapshotfs.(*Uploader).processSingle(0xc005462160, {0x1dd7360, 0xc0053782d0}, {0x1ddffd8?, 0xc0a2760030}, {0xc0a24ffa90, 0x47}, 0x4095b2?, 0xc0050f7428, {0xc0a2322bf0, ...}, ...)
	/home/runner/work/kopia/kopia/snapshot/snapshotfs/upload.go:863 +0x391
github.com/kopia/kopia/snapshot/snapshotfs.(*Uploader).processDirectoryEntries.func1.1(0xc05d7b5fa8?, 0xc0a2754230)
	/home/runner/work/kopia/kopia/snapshot/snapshotfs/upload.go:786 +0x9d
github.com/kopia/kopia/internal/workshare.NewPool[...].func1()
	/home/runner/work/kopia/kopia/internal/workshare/workshare_pool.go:61 +0x8b
created by github.com/kopia/kopia/internal/workshare.NewPool[...] in goroutine 1
	/home/runner/work/kopia/kopia/internal/workshare/workshare_pool.go:54 +0xd1
                                                                                
```

**Comment by julio-lopez** [comment]
It seems like time went backwards here.

What is the setup, is it a laptop, desktop or container? How is the clock synchronized, what's the time source and so on?
 
We could add a safeguard to prevent the panic, but that would only mask the cause of the issue.

**Comment by saviodsouza** [comment]
This repository contains a snapshots from a couple of windows and Linux
boxes

This error was specific to one linux box home folder only.

I had run an apt update/ upgrade after which kopia got upgraded to v14 from
v13.
The kopia clear cache did not help

I downloaded kopia v13.0 did a kopia snapshot create and it worked
Again tried with kopia 14 and it looks normal.

I'll wait and see after creating snapshots from all sources with v14 this
weekend and see if I can reproduce the issue.



Thanks @***@***.*** ***@***.***>

**Comment by julio-lopez** [comment]
@saviodsouza Thanks for the followup.

For what I can gather from your reply,

- This happened on a Linux box, is that right?
- Is this box a host that is turned on all the time, like a server? Or is it a laptop?
- How is time synchronized in this box? is NTP configured?
- How is `kopia` running on this box?
    1. directly on the host (bare metal);
    2. in a VM;
    3. inside a container;
    4. inside a container on a VM?

Thanks.

**Comment by aron123** [comment]
This error occurred to me as well, when I ran Kopia directly in a VirtualBox VM.

My host machine is a notebook with Windows 11. The guest machine is a virtualbox with Ubuntu 22.04, network time synchronization is turned off. VirtualBox 7.0.10 r158379 (Qt5.15.2) was used for virtualization.

**Comment by saviodsouza** [comment]
A virtual box vm

Out of which only 1 of 4 snapshot sources in the - virtual box vm was affected with this error.

This happened on a Linux box, is that right?
Yes error in the linux virtual box vm with windows host outside

Is this box a host that is turned on all the time, like a server? Or is it a laptop?
A laptop not turned on full time

How is time synchronized in this box? is NTP configured?
Windows time service

How is kopia running on this box?
Usb disk connected directly on bare metal, pass thru the vbox vm, mounted in the vm and run kopia snapshot create --all




I have tried these couple of days repeatedly and I am unable to reproduce the error.


I think you may be right that there might have been some issue with the time sync when I tried earlier.

**Comment by julio-lopez** [comment]
Yes, it sounds like from the setup that there is an issue with how time is presented to processes in the VM.
We could prevent this error by logging instead of letting it panic. However, as stated before, this may end up actually masking a real problem and actually end up causing more problems. Parts of kopia, such as maintenance and space reclamation assume that time is moving forward and put bounds on the maximum tolerated clock drift. So.

**Comment by thomaspant** [comment]
I get the same error. I am using Kopia with Velero. The setup is the following:
- 2 VirtualBox VMs with Ubuntu Server 23.10 OS (kernel:  Linux 6.5.0-25-generic) that form a k3s cluster 
- another VM with the same configuration as a MinIO server for the Velero BackupStorageLocation
- Longhorn for storage
- Velero for Backups/Restores

These 3 VMs are time synced using timedatectl (I also tried chrony with the same result).

When I try to create a File System Backup of a Longhorn Volume that has many files (about 100000 or more), the File System Backup of the Volume fails. When there are not too many files in the Volume the backup is created normally.

The error I get (in the node-agent pod of Velero) is the following:
```
time="2024-03-01T15:43:54Z" level=info msg="Searching for parent snapshot" backup=velero/fs6 controller=podvolumebackup logSource="pkg/uploader/kopia/snapshot.go:259" parentSnapshot= path="/host_pods/6016c3e7-8017-4b6e-8d5e-fe3ff9c9d20e/volumes/kubernetes.io~csi/pvc-175d1733-2bf8-410d-8a30-18b47d7195a9/mount" podvolumebackup=velero/fs6-dtkr5 realSource=
panic: counter cannot decrease in value

goroutine 2178 [running]:
github.com/prometheus/client_golang/prometheus.(*counter).Add(0x423fcc0?, 0xc1709bce9047b879?)
        /go/pkg/mod/github.com/prometheus/client_golang@v1.17.0/prometheus/counter.go:128 +0xe9
github.com/kopia/kopia/internal/metrics.(*Counter).Add(...)
        /go/pkg/mod/github.com/project-velero/kopia@v0.0.0-20231023031817-cf7bbc7f8519/internal/metrics/metrics_counter.go:22
github.com/kopia/kopia/internal/metrics.(*Throughput).Observe(0xc000112120?, 0xa?, 0xffffffffffffbee1)
        /go/pkg/mod/github.com/project-velero/kopia@v0.0.0-20231023031817-cf7bbc7f8519/internal/metrics/metrics_throughput.go:20 +0x8b
github.com/kopia/kopia/repo/content.(*WriteManager).WriteContent.func1()
        /go/pkg/mod/github.com/project-velero/kopia@v0.0.0-20231023031817-cf7bbc7f8519/repo/content/content_manager.go:780 +0xec
github.com/kopia/kopia/repo/content.(*WriteManager).WriteContent(0xc000b61340, {0x2dd7650, 0xc00271ee40}, {{0xc00270ff68, 0x1, 0x1}, {{0xc004120000, 0xa, 0x10000}}}, {0x0, ...}, ...)
        /go/pkg/mod/github.com/project-velero/kopia@v0.0.0-20231023031817-cf7bbc7f8519/repo/content/content_manager.go:832 +0x90b
github.com/kopia/kopia/repo/object.(*objectWriter).prepareAndWriteContentChunk(0xc0003130e0, 0x0, {{0xc00270ff68, 0x1, 0x1}, {{0xc004120000, 0xa, 0x10000}}})
        /go/pkg/mod/github.com/project-velero/kopia@v0.0.0-20231023031817-cf7bbc7f8519/repo/object/object_writer.go:208 +0x289
github.com/kopia/kopia/repo/object.(*objectWriter).flushBuffer.func1()
        /go/pkg/mod/github.com/project-velero/kopia@v0.0.0-20231023031817-cf7bbc7f8519/repo/object/object_writer.go:173 +0x12f
created by github.com/kopia/kopia/repo/object.(*objectWriter).flushBuffer in goroutine 2025
        /go/pkg/mod/github.com/project-velero/kopia@v0.0.0-20231023031817-cf7bbc7f8519/repo/object/object_writer.go:165 +0x345
```

Is there any workaround to this? Is there any plan that it gets fixed?

**Comment by juhrmann** [comment]
The issue is still there.
Unfortunately, the following workarounds have no effect:

1. Disabling time synchronization via VBoxAdditions as described in the [VirtualBox manual](https://docs.oracle.com/en/virtualization/virtualbox/6.0/admin/fine-tune-timers.html)
2. Disabling the time synchronization of systemd. `systemctl stop systemd-timesyncd.service`
3. Disabling guest additions: `systemctl stop vboxservice.service`

Are there any other hints? I would love to use kopia for my backups.
