### ISSUE TITLE
MacOS: `cli` package of `make ci-tests` fails:  Upgrade `mmap` implementation.

### ISSUE THREAD

**Issue by aaron-kasten** [kopia/kopia#3474]
`kopia/tools/.tools/gotestsum-1.10.0/gotestsum --debug --format=standard-verbose --no-summary=skipped --jsonfile=.tmp.unit-tests.json -- -v -tags testing -count=1 -timeout 1200s ./...` fails in `cli` package with the following error:

```
unexpected fault address 0x14dfb4011
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x2 addr=0x14dfb4011 pc=0x1048d803c]

goroutine 6010 [running]:
runtime.throw({0x10514b5bf?, 0x73?})
	/opt/local/lib/go/src/runtime/panic.go:1077 +0x40 fp=0x140001ffc70 sp=0x140001ffc40 pc=0x10445a980
runtime.sigpanic()
	/opt/local/lib/go/src/runtime/signal_unix.go:875 +0x22c fp=0x140001ffcd0 sp=0x140001ffc70 pc=0x1044729bc
github.com/kopia/kopia/repo/content/index.bytesToContentID(...)
	/Users/aaron.alpar/devel/kopia/repo/content/index/content_id_to_bytes.go:14
github.com/kopia/kopia/repo/content/index.(*indexV2).findEntryPosition.func1(0x140005b25c8?)
	/Users/aaron.alpar/devel/kopia/repo/content/index/index_v2.go:330 +0xcc fp=0x140001ffd90 sp=0x140001ffce0 pc=0x1048d803c
sort.Search(0x140005b2648?, 0x140001ffdf0)
	/opt/local/lib/go/src/sort/search.go:65 +0x48 fp=0x140001ffdc0 sp=0x140001ffd90 pc=0x1044c2f28
github.com/kopia/kopia/repo/content/index.(*indexV2).findEntryPosition(0x14002718dd8?, {0x105149be3?, 0x140005b2668?})
	/Users/aaron.alpar/devel/kopia/repo/content/index/index_v2.go:319 +0x58 fp=0x140001ffe20 sp=0x140001ffdc0 pc=0x1048d7f38
github.com/kopia/kopia/repo/content/index.(*indexV2).Iterate(0x14002e621b0, {{0x105149be3?, 0x0?}, {0x14001b79178?, 0x105939380?}}, 0x140036aaa98)
	/Users/aaron.alpar/devel/kopia/repo/content/index/index_v2.go:281 +0x38 fp=0x140001fff10 sp=0x140001ffe20 pc=0x1048d7c28
github.com/kopia/kopia/repo/content/index.iterateChan.func1()
	/Users/aaron.alpar/devel/kopia/repo/content/index/merged.go:123 +0x124 fp=0x140001fffd0 sp=0x140001fff10 pc=0x1048db334
runtime.goexit()
	/opt/local/lib/go/src/runtime/asm_arm64.s:1197 +0x4 fp=0x140001fffd0 sp=0x140001fffd0 pc=0x104492554
created by github.com/kopia/kopia/repo/content/index.iterateChan in goroutine 2157
	/Users/aaron.alpar/devel/kopia/repo/content/index/merged.go:119 +0x128
```

The structure at `0x14dfb4011` is part of a synthetic slice.  The slide is part of mmaped memory produced by `github.com/edsrzf/mmap-go` - which is suspect because of its age relative to Apple Silicon.

Investigate using the `/x/exp` package mmap libraries as a replacement (which is actively maintained).

**Comment by julio-lopez** [comment]
@aaron-kasten just to verify, is this using "HEAD@master" ? There was a change ~month ago for how content infos obtained from the indices. The objective of that change was to copy the content info into its own memory instead of using something backed by mapped memory.

Could you please share the commit id (that is in master) that you are using?

**Comment by aaron-kasten** [comment]
`commit d4a380f7c115af60cde86eeb77cffa8441ec78b8 (upstream/master, origin/master, master)`

> @aaron-kasten just to verify, is this using "HEAD@master" ? There was a change ~month ago for how content infos obtained from the indices. The objective of that change was to copy the content info into its own memory instead of using something backed by mapped memory.
> 
> Could you please share the commit id (that is in master) that you are using?

**Comment by aaron-kasten** [comment]
NOTE: The errors are occurring in my PPROF branch which is based on master.  The errors and suspect allocation are in a location independent of the PPROF branch.  The tests above succeed when `cli` tests are run alone.  `cli` tests only fail when run as part of the suite: `make ci-tests`

**Comment by julio-lopez** [comment]
@aaron-kasten Understood, just verifying that your branch was based on a recent commit.

**Comment by jkowalski** [comment]
Pretty sure this has nothing to do with mmap implementation, it looks like some data corruption. Can you repro this reliably? I have M1 and am not seeing this issue.

**Comment by aaron-kasten** [comment]
@jkowalski I think you are correct.  The mmap libraries may be out-of-date - but not in a way that will prevent a correct file mmap.

This problem turned out to be a race in Kopia.  The long standing problem was the exit error setting, which was exasperated by the PPROF settings (the large buffers alloced by PPROF).

As far as the fix:
- I've put a mutex in the PPROF dumps so that PPROF setup and teardown runs single threaded and does not interfere with other operations.
- The exit error code also uses channel to collect the exit errors and produce a single multierror.

Both of these seem to fix the SEGV flakeyness in Darwin ARM.

**Comment by aaron-kasten** [comment]
I'm going to wait and close this once the fixes are merged.
