### ISSUE TITLE
Windows test failing due to broken scheduling ...

### ISSUE THREAD

**Issue by aaron-kasten** [kopia/kopia#3624]
`TestServerScheduling` fails with:

```
    server_start_test.go:481: server-finished in 6: 'kopia --config-file C:\Users\aaron\AppData\Local\Temp\kopia-test4030917212\.kopia.config --no-use-credential-manager snapshot list -l --manifest-id C:\Users\aaron\AppData\Local\Temp\kopia-test2632750119'
    server_start_test.go:484:
                Error Trace:    C:/Users/aaron/devel/kopia/tests/end_to_end_test/server_start_test.go:484
                Error:          "3" is not greater than or equal to "8"
                Test:           TestServerScheduling
    panic.go:523: server-running 'kopia --config-file C:\Users\aaron\AppData\Local\Temp\kopia-test4030917212\.kopia.config --no-use-credential-manager repo disconnect' with map[KOPIA_PASSWORD:qWQPJ2hiiLgWRRCr]
    panic.go:523: server-finished in 9: 'kopia --config-file C:\Users\aaron\AppData\Local\Temp\kopia-test4030917212\.kopia.config --no-use-credential-manager repo disconnect'
    tmpdir.go:64: temporary files left in C:\Users\aaron\AppData\Local\Temp\kopia-test2632750119
    tmpdir.go:64: temporary files left in C:\Users\aaron\AppData\Local\Temp\kopia-test1874078142
    tmpdir.go:64: temporary files left in C:\Users\aaron\AppData\Local\Temp\kopia-test2378839324
    tmpdir.go:64: temporary files left in C:\Users\aaron\AppData\Local\Temp\kopia-test4030917212
FAIL
FAIL    github.com/kopia/kopia/tests/end_to_end_test    25.715s
FAIL
```

Reproduce with:
```
go test -run "^TestServerScheduling$" -tags testing -count=1 -parallel=1 -timeout 1200s github.com/kopia/kopia/tests/end_to_end_test
```

Suspect commit:
```
f62ef51700149d387a657ddbc3899be2e6300a7b is the first bad commit
commit f62ef51700149d387a657ddbc3899be2e6300a7b
Author: Maxim Khitrov <max@mxcrypt.com>
Date:   Sun Feb 4 00:44:41 2024 -0500

    feat(snapshots): Implement volume shadow copy support on Windows (#3543)

    * Implement volume shadow copy support on Windows

    * Update go-vss version

    * Fix unused variables

    * Rename upload_actions*.go files

    * Move vss settings to a separate policy section

    * Handle existing shadow copy root

 ```

Trivia:
Commit also fails when `-race` testing.  May be caused by CGO bug.
```
PS C:\Users\aaron\devel\kopia> go test -run "^TestServerScheduling$" -race -tags testing -count=1 -parallel=1 -timeout 1200s github.com/kopia/kopia/tests/end_to_end_test
fatal error: checkptr: pointer arithmetic result points to invalid allocation

goroutine 271 [running, locked to thread]:
runtime.throw({0x141e40471?, 0x14000b1fd?})
        C:/Program Files/Go/src/runtime/panic.go:1077 +0x65 fp=0xc00171bb60 sp=0xc00171bb30 pc=0x14003fb85
runtime.checkptrArithmetic(0xc00171c0d8?, {0x0, 0x0, 0x0?})
        C:/Program Files/Go/src/runtime/checkptr.go:69 +0x9c fp=0xc00171bb90 sp=0xc00171bb60 pc=0x14000b39c
github.com/go-ole/go-ole.invoke(0x70ca18, 0x1000001, 0x1, {0xc00171c320, 0x3, 0x0?})
        C:/Users/aaron/go/pkg/mod/github.com/go-ole/go-ole@v1.3.0/idispatch_windows.go:199 +0x2476 fp=0xc00171c158 sp=0xc00171bb90 pc=0x140f729b6
github.com/go-ole/go-ole.(*IDispatch).Invoke(...)
        C:/Users/aaron/go/pkg/mod/github.com/go-ole/go-ole@v1.3.0/idispatch.go:27
github.com/go-ole/go-ole.(*IDispatch).InvokeWithOptionalArgs(0xc0003f3e5d?, {0x141dde5ee, 0x6}, 0x1?, {0xc00171c320, 0x3, 0x3})
        C:/Users/aaron/go/pkg/mod/github.com/go-ole/go-ole@v1.3.0/idispatch.go:71 +0xae fp=0xc00171c1b8 sp=0xc00171c158 pc=0x140f6fb2e
github.com/go-ole/go-ole.(*IDispatch).CallMethod(...)
        C:/Users/aaron/go/pkg/mod/github.com/go-ole/go-ole@v1.3.0/idispatch.go:79
github.com/mxk/go-vss.create(0x70b198, {0xc0003f3e5d, 0x3})
        C:/Users/aaron/go/pkg/mod/github.com/mxk/go-vss@v1.2.0/vss.go:324 +0x37a fp=0xc00171c390 sp=0xc00171c1b8 pc=0x140f7e25a
github.com/mxk/go-vss.Create.func1(0x0?)
        C:/Users/aaron/go/pkg/mod/github.com/mxk/go-vss@v1.2.0/vss.go:39 +0x50 fp=0xc00171c3f0 sp=0xc00171c390 pc=0x140f7c890
github.com/mxk/go-vss.wmiExec(0xc00171c4f8)
```

See: https://github.com/kopia/kopia/actions/runs/7792015952/job/21249231676 for example failure in workflows test.

**Comment by julio-lopez** [comment]
fixed by #3625
