### ISSUE TITLE
Kopia server crashes when launching a server on a client host

### ISSUE THREAD

**Issue by sjthespian** [kopia/kopia#3631]
I have a Kopia server running connected to my home minio server that runs fine. I am planning on setting up a systemd config for it at some point, but since I am still testing things I start I with:
```shell
sudo kopia server start --insecure --address '[::]:51515' --server-username kopia@$(hostname) --tls-cert-file /etc/kopia/kopia.cert --tls-key-file /etc/kopia/kopia.key --without-password  &
```
The certs are self-signed certs generated with `--tls-generate-cert` (eventually they will be from LetsEncrypt).

I am able to connect a remote client to it and successfully snapshot that client:
```shell
sudo kopia repository connect server --url https://172.16.xx.xx:51515 --server-cert-fingerprint xxxxxxxxxxxxxxxxx
sudo kopia snapshot create  /
Snapshotting root@conpi:/ ...
 | 2 hashing, 432 hashed (34.4 MB), 0 cached (0 B), uploaded 34.3 MB, estimating...
 ! Ignored error when processing "var/agentx/master": unknown or unsupported entry type
 * 0 hashing, 110331 hashed (2.8 GB), 0 cached (0 B), uploaded 2.4 GB (1 errors ignored), estimated 2.8 GB (100.2%) 0s left
Created snapshot with root xxxxxxxx and ID xxxxxxxx in 12m54s
WARN Ignored 1 error(s) while snapshotting root@xxxxxx:/.
```

Since I want to be able to schedule snapshots on that client, I decided to start up a server:
```shell
sudo kopia server start --address '[::]:51515'

Server will allow connections from users whose accounts are stored in the repository.
User accounts can be added using 'kopia server user add'.

ERROR failed to open repository: unable to establish session for purpose=: error establishing session: unable to initialize session: rpc error: code = Unavailable desc = error reading from server: EOF: EOF
ERROR unable to initialize repository: unable to initialize repository: error opening repository: unable to open repository: unable to establish session for purpose=: error establishing session: unable to initialize session: rpc error: code = Unavailable desc = error reading from server: EOF: EOF
```

And at the same time, the kolpia server that client is using crashes with a stack trace:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xd2be91]

goroutine 523 [running]:
github.com/kopia/kopia/internal/server.(*Server).authenticateGRPCSession(0xc0002da000, {0x1d3c330, 0xc005c73410}, {0x7f48b712f140, 0xc005562840})
	/home/runner/work/kopia/kopia/internal/server/grpc_session.go:65 +0x191
github.com/kopia/kopia/internal/server.(*Server).Session(0xc0002da000, {0x1d43488, 0xc005c0f6c0})
	/home/runner/work/kopia/kopia/internal/server/grpc_session.go:87 +0x13d
github.com/kopia/kopia/internal/grpcapi._KopiaRepository_Session_Handler({0x160f760?, 0xc0002da000}, {0x1d401c0?, 0xc005fc8000})
	/home/runner/work/kopia/kopia/internal/grpcapi/repository_server_grpc.pb.go:98 +0x91
google.golang.org/grpc.(*Server).processStreamingRPC(0xc005c82b40, {0x1d441e0, 0xc005c1ed20}, 0xc005fbe240, 0xc005cb6de0, 0x2737c00, 0x0)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.58.2/server.go:1670 +0x12e8
google.golang.org/grpc.(*Server).handleStream(0xc005c82b40, {0x1d441e0, 0xc005c1ed20}, 0xc005fbe240, 0x0)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.58.2/server.go:1757 +0x9a6
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.58.2/server.go:998 +0x8d
created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 520
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.58.2/server.go:996 +0x165
```

I'm assuming the solution to this crash is "don't do that", but in any case I would expect to get an error from the client on starting the server, not a crash from the primary server.

Is there a proper way to schedule snapshots on clients of a kopia server short of setting up a cron job to run them if I can't run a server there?

The above is happening on Ubuntu 22.04 on the server and Debian 10 on the client. Both are running kopia 0.15.0.

**Comment by juanafanador07** [comment]
I have faced the same issue. Aparently, --without-password makes the server crash. Try removing it

**Comment by sjthespian** [comment]
> I have faced the same issue. Aparently, --without-password makes the server crash. Try removing it. This was discussed in issue #3132

If I can get the server reliably working without that I'll give it a try... Even when I put the password in the command line arguments, I still can't get it to log in consistently.

**Comment by sjthespian** [comment]
@juanafanador07 Thanks for the tip, it looks like that does the trick! And as a side effect, it forced me to get a systemd service file written so I can do this will all of my systems!

If anyone is interested, here's the /etc/default/kopia and systemd service file I'm using...
/etc/default/kopia
```
KOPIA_SERVER_USERNAME=kopia
KOPIA_SERVER_PASSWORD=password
KOPIA_CONFIG_PATH=/etc/kopia/config/repository.config
KOPIA_REPO_PASSWORD=really_strong_password

## Uncomment and specify cert locations if using TLS certificates
KOPIA_CERT_ARGS=--tls-cert-file /etc/kopia/kopia.cert --tls-key-file /etc/kopia/kopia.key

## If additional arguments are needed for the server, add them here
KOPIA_ADDITIONAL_ARGS=
```

/etc/systemd/system/kopia.service:
```
[Unit]
Description=Kopia Server
After=syslog.target
After=network.target

[Service]
User=root
Type=simple
EnvironmentFile=-/etc/default/kopia
ExecStart=kopia server start --address "[::]:51515" $KOPIA_CERT_ARGS $KOPIA_ADDITIONAL_ARGS --password="${KOPIA_REPO_PASSWORD}"
ExecStop=kopia server shutdown
Restart=always
RestartSec=60

[Install]
WantedBy=multi-user.target
```

**Comment by cecabrera** [comment]
Tested multiple paths to restore the data assuming the kopia server is not available by restoring the data just from the data in GCP (my case, yours AWS S3) and it wasn't possible. So I need to have access to the main Kopia Server to desencrypt my data in GCP. What I have faced is that I cannot use a `client` version of Kopia to just consume the data, use my password and restore the files. Could I be missing something?
