### ISSUE TITLE
Random failure of maintenance jobs

### ISSUE THREAD

**Issue by prashanthpx** [kopia/kopia#3650]
Hi,
Have been using kopia for long time in kuberneets environment to backup PVC data and offlate have started observing the following error of maintenace jobs
```
time="2024-02-15T12:08:29Z" level=info msg="kopia repo connect successful .."
time="2024-02-15T12:08:29Z" level=info msg="connect to repo completed successfully for repository [generic-backup/mysql-dummy-pvc-1/]"
2024/02/15 12:08:29 maintenance set command status not available Next retry in: 5s
2024/02/15 12:08:34 maintenance set command status not available Next retry in: 5s
2024/02/15 12:08:39 maintenance set command status not available Next retry in: 5s
2024/02/15 12:08:44 maintenance set command status not available Next retry in: 5s
2024/02/15 12:08:49 maintenance set command status not available Next retry in: 5s
2024/02/15 12:08:54 maintenance set command status not available Next retry in: 5s
2024/02/15 12:08:59 maintenance set command status not available Next retry in: 5s
2024/02/15 12:09:04 maintenance set command status not available Next retry in: 5s
2024/02/15 12:09:09 maintenance set command status not available Next retry in: 5s
2024/02/15 12:09:14 maintenance set command status not available Next retry in: 5s
2024/02/15 12:09:19 maintenance set command status not available Next retry in: 5s
2024/02/15 12:09:24 maintenance set command status not available Next retry in: 5s
time="2024-02-15T12:09:29Z" level=error msg="runMaintenance:: maintenance owner set command failed for repo [generic-backup/mysql-dummy-pvc-1/]: timed out performing task., Error was: context deadline exceeded"
time="2024-02-15T12:09:29Z" level=info msg="Repository connect started"
2024/02/15 12:09:29 repository connect status not available Next retry in: 5s
time="2024-02-15T12:09:31Z" level=error msg="failed to run the kopia connect command: exit status 1 stdout:  stderr: \x1b[31mERROR\x1b[0m failed to open repository: unable to create shared content manager: error loading indexes: error downloading indexes: error loading index blob xn0_002eb09168ccda7a9ceb73d3b9bf209f-sbd4804f4f27ff166125-c1: decrypt blob: error decrypting BLOB xn0_002eb09168ccda7a9ceb73d3b9bf209f-sbd4804f4f27ff166125-c1: unable to decrypt content: cipher: message authentication failed\n\x1b[31mERROR\x1b[0m unable to disconnect after unsuccessful opening: remove /tmp/kopiaconfig: no such file or directory\n\x1b[31mERROR\x1b[0m error connecting to repository: unable to create shared content manager: error loading indexes: error downloading indexes: error loading index blob xn0_002eb09168ccda7a9ceb73d3b9bf209f-sbd4804f4f27ff166125-c1: decrypt blob: error decrypting BLOB xn0_002eb09168ccda7a9ceb73d3b9bf209f-sbd4804f4f27ff166125-c1: unable to decrypt content: cipher: message authentication failed\n2024-02-15 12:09:31.546358438 +0000 UTC write error: unable to open log file: open /tmp/cli-logs/kopia-20240215-120929-54-repository-connect-s3.1.log: no such file or directory\n"
ERROR failed to open repository: unable to create shared content manager: error loading indexes: error downloading indexes: error loading index blob xn0_002eb09168ccda7a9ceb73d3b9bf209f-sbd4804f4f27ff166125-c1: decrypt blob: error decrypting BLOB xn0_002eb09168ccda7a9ceb73d3b9bf209f-sbd4804f4f27ff166125-c1: unable to decrypt content: cipher: message authentication failed
ERROR unable to disconnect after unsuccessful opening: remove /tmp/kopiaconfig: no such file or directory
ERROR error connecting to repository: unable to create shared content manager: error loading indexes: error downloading indexes: error loading index blob xn0_002eb09168ccda7a9ceb73d3b9bf209f-sbd4804f4f27ff166125-c1: decrypt blob: error decrypting BLOB xn0_002eb09168ccda7a9ceb73d3b9bf209f-sbd4804f4f27ff166125-c1: unable to decrypt content: cipher: message authentication failed
2024-02-15 12:09:31.546358438 +0000 UTC write error: unable to open log file: open /tmp/cli-logs/kopia-20240215-120929-54-repository-connect-s3.1.log: no such file or directory
```

This is also impact backups as furhter backups to the repo are failing. Any clue on what could be going wrong?
With this state, i am not able to perform any repair also as the `kopia connect` always fails.

**Comment by jkowalski** [comment]
this could be either invalid password or actual data corruption.

Is there a chance you re-created the repository in the same storage and some old non-decryptable blobs are messing it up?

**Comment by prashanthpx** [comment]
> this could be either invalid password or actual data corruption.
> 
> Is there a chance you re-created the repository in the same storage and some old non-decryptable blobs are messing it up?

Thanks for the reply.
1. Password is not changed as its hardcoded in my kubernetes job.
2. This repository was same and runnin backups successful and it started throwing this error.
Also baclup failures happens post this error (sometime and not all the times)

```
time="2024-01-19T11:26:32Z" level=error msg="failed to run the kopia connect command: exit status 1 stdout:  stderr: \x1b[31mERROR\x1b[0m unable to add xr72_79_882a657e44a06f295462a3ab5ecd31b8-s31f34da7476b728a-c1 to metadata cache: context canceled\n\x1b[31mERROR\x1b[0m unable to add xr80_87_c879f60129f58ec25d6deb2a2b79c3f8-scb10668d7da5ad69-c1 to metadata cache: context canceled\n\x1b[31mERROR\x1b[0m unable to add xr96_103_037c31505cfc1d94bf73f878024c7733-s1ce70372fbc85cde-c1 to metadata cache: context canceled\n\x1b[31mERROR\x1b[0m unable to add xr88_95_02a3c667cf931aee89abfa4a4557431f-s262ef955d4493dd4-c1 to metadata cache: context canceled\n\x1b[31mERROR\x1b[0m failed to open repository: unable to create shared content manager: error loading indexes: error downloading indexes: error loading index blob xr64_71_6bfe0eb9d32a51c9b97e54ff65882da3-s3c71a405b43a5ab4-c1: error decrypting BLOB xr64_71_6bfe0eb9d32a51c9b97e54ff65882da3-s3c71a405b43a5ab4-c1: unable to decrypt content: cipher: message authentication failed\n\x1b[31mERROR\x1b[0m unable to disconnect after unsuccessful opening: remove /tmp/kopiaconfig: no such file or directory\nkopia: error: error connecting to repository: unable to create shared content manager: error loading indexes: error downloading indexes: error loading index blob xr64_71_6bfe0eb9d32a51c9b97e54ff65882da3-s3c71a405b43a5ab4-c1: error decrypting BLOB xr64_71_6bfe0eb9d32a51c9b97e54ff65882da3-s3c71a405b43a5ab4-c1: unable to decrypt content: cipher: message authentication failed, try --help\n"
[31mERROR[0m unable to add xr72_79_882a657e44a06f295462a3ab5ecd31b8-s31f34da7476b728a-c1 to metadata cache: context canceled
[31mERROR[0m unable to add xr80_87_c879f60129f58ec25d6deb2a2b79c3f8-scb10668d7da5ad69-c1 to metadata cache: context canceled
[31mERROR[0m unable to add xr96_103_037c31505cfc1d94bf73f878024c7733-s1ce70372fbc85cde-c1 to metadata cache: context canceled
[31mERROR[0m unable to add xr88_95_02a3c667cf931aee89abfa4a4557431f-s262ef955d4493dd4-c1 to metadata cache: context canceled
[31mERROR[0m failed to open repository: unable to create shared content manager: error loading indexes: error downloading indexes: error loading index blob xr64_71_6bfe0eb9d32a51c9b97e54ff65882da3-s3c71a405b43a5ab4-c1: error decrypting BLOB xr64_71_6bfe0eb9d32a51c9b97e54ff65882da3-s3c71a405b43a5ab4-c1: unable to decrypt content: cipher: message authentication failed
[31mERROR[0m unable to disconnect after unsuccessful opening: remove /tmp/kopiaconfig: no such file or directory
kopia: error: error connecting to repository: unable to create shared content manager: error loading indexes: error downloading indexes: error loading index blob xr64_71_6bfe0eb9d32a51c9b97e54ff65882da3-s3c71a405b43a5ab4-c1: error decrypting BLOB xr64_71_6bfe0eb9d32a51c9b97e54ff65882da3-s3c71a405b43a5ab4-c1: unable to decrypt content: cipher: message authentication failed, try --help

```

Once backup failure happens, i am not able to run any kopia commands and the only way is to destroy the reposiotry and create a new one. I have seen this happeniong 3 to 4 times till now.
If it's data corruption, is there a way to recover? I am afraid even for recovery steps we need to connect to repository which also fails.

**Comment by jkowalski** [comment]
what is the underlying storage you're backing up to?

**Comment by prashanthpx** [comment]
> what is the underlying storage you're backing up to?

S3 storage

**Comment by prashanthpx** [comment]
Seeing below error sometimes
```
time="2024-02-27T01:09:49Z" level=info msg="connect to repo completed successfully for repository [generic-backup/infraconnectdirect-anthos-cl-pa5-ibm-connect-direct-pvc/]"
2024/02/27 01:09:49 maintenance set command status not available Next retry in: 5s
time="2024-02-27T01:09:54Z" level=info msg="maintenance set owner command completed successfully for repository [generic-backup/infraconnectdirect-anthos-cl-pa5-ibm-connect-direct-pvc/]"
time="2024-02-27T01:10:04Z" level=info msg="maintenance full run command completed successfully for repository [generic-backup/infraconnectdirect-anthos-cl-pa5-ibm-connect-direct-pvc/]"
time="2024-02-27T01:10:04Z" level=info msg="Repository connect started"
2024/02/27 01:10:04 repository connect status not available Next retry in: 5s
time="2024-02-27T01:10:07Z" level=error msg="failed to run the kopia connect command: exit status 2 stdout:  stderr: \x1b[33mWARN\x1b[0m invalid list cache HMAC for xr, ignoring\n\x1b[33mWARN\x1b[0m invalid list cache HMAC for xe, ignoring\n\x1b[33mWARN\x1b[0m invalid list cache HMAC for xs, ignoring\npanic: runtime error: makeslice: len out of range\n\ngoroutine 1 [running]:\ngithub.com/kopia/kopia/internal/epoch.(*Manager).getCompleteIndexSetForCommittedState(0xc00043e360, {0x17f2bc8, 0xc000010420}, {0x23, 0xc005084c60, {0xc00047ac60, 0xc, 0xc}, 0xc0003a6150, 0xc0003a60f0, ...}, ...)\n\t/home/runner/work/kopia/kopia/internal/epoch/epoch_manager.go:747 +0x3e7\ngithub.com/kopia/kopia/internal/epoch.(*Manager).GetCompleteIndexSet(0xc00043e360, {0x17f2bc8, 0xc000010420}, 0x40ce34)\n\t/home/runner/work/kopia/kopia/internal/epoch/epoch_manager.go:659 +0x1d5\ngithub.com/kopia/kopia/repo/content.(*indexBlobManagerV1).listActiveIndexBlobs(0xc000228190, {0x17f2bc8, 0xc000010420})\n\t/home/runner/work/kopia/kopia/repo/content/index_blob_manager_v1.go:29 +0x69\ngithub.com/kopia/kopia/repo/content.(*SharedManager).loadPackIndexesLocked(0xc00000a1e0, {0x17f2bc8, 0xc000010420})\n\t/home/runner/work/kopia/kopia/repo/content/committed_read_manager.go:191 +0x1d8\ngithub.com/kopia/kopia/repo/content.NewSharedManager({0x17f2bc8, 0xc000010420}, {0x180cfc8, 0xc0002f2090}, 0xc00004a0c0, 0xc00028f548, 0x21)\n\t/home/runner/work/kopia/kopia/repo/content/committed_read_manager.go:576 +0x588\ngithub.com/kopia/kopia/repo.openWithConfig({0x17f2bc8, 0xc000010420}, {0x180cfc8, 0xc0002f2090}, 0xc000328cc0, {0x7ffeaee3124a, 0x8}, 0xc00028f7f8, 0xc000136f98, {0x7ffeaee312bd, ...})\n\t/home/runner/work/kopia/kopia/repo/open.go:225 +0x425\ngithub.com/kopia/kopia/repo.openDirect({0x17f2bc8, 0xc000010420}, {0x7ffeaee312bd, 0x10}, 0xc000328cc0, {0x7ffeaee3124a, 0x8}, 0xc0006717f8)\n\t/home/runner/work/kopia/kopia/repo/open.go:157 +0x207\ngithub.com/kopia/kopia/repo.Open({0x17f2bc8, 0xc000010420}, {0x7ffeaee312bd, 0xc0004f6cc0}, {0x7ffeaee3124a, 0x8}, 0xc000145ca0)\n\t/home/runner/work/kopia/kopia/repo/open.go:90 +0x2b3\ngithub.com/kopia/kopia/repo.verifyConnect({0x17f2bc8, 0xc000010420}, {0x7ffeaee312bd, 0x10}, {0x7ffeaee3124a, 0x2d})\n\t/home/runner/work/kopia/kopia/repo/connect.go:67 +0x45\ngithub.com/kopia/kopia/repo.Connect({0x17f2bc8, 0xc000010420}, {0x7ffeaee312bd, 0x10}, {0x180cfc8, 0xc00020b890}, {0x7ffeaee3124a, 0x8}, 0x0)\n\t/home/runner/work/kopia/kopia/repo/connect.go:62 +0x573\ngithub.com/kopia/kopia/cli.(*App).runConnectCommandWithStorageAndPassword(0xc000456000, {0x17f2bc8, 0xc000010420}, 0xc000457528, {0x180cfc8, 0xc00020b890}, {0x7ffeaee3124a, 0x8})\n\t/home/runner/work/kopia/kopia/cli/command_repository_connect.go:118 +0x1fe\ngithub.com/kopia/kopia/cli.(*App).runConnectCommandWithStorage(0x0, {0x17f2bc8, 0xc000010420}, 0x0, {0x180cfc8, 0xc00020b890})\n\t/home/runner/work/kopia/kopia/cli/command_repository_connect.go:112 +0x9e\ngithub.com/kopia/kopia/cli.(*commandRepositoryConnect).setup.func1(0x1279d62)\n\t/home/runner/work/kopia/kopia/cli/command_repository_connect.go:41 +0xcb\ngithub.com/alecthomas/kingpin.(*actionMixin).applyActions(0x1, 0xc00024fba0)\n\t/home/runner/go/pkg/mod/github.com/alecthomas/kingpin@v0.0.0-20200323085623-b6657d9477a6/actions.go:28 +0x5c\ngithub.com/alecthomas/kingpin.(*Application).applyActions(0xc000462000, 0xc000318480)\n\t/home/runner/go/pkg/mod/github.com/alecthomas/kingpin@v0.0.0-20200323085623-b6657d9477a6/app.go:560 +0xa2\ngithub.com/alecthomas/kingpin.(*Application).execute(0xc000462000, 0xc000318480, {0xc0004f7e80, 0x3, 0x4})\n\t/home/runner/go/pkg/mod/github.com/alecthomas/kingpin@v0.0.0-20200323085623-b6657d9477a6/app.go:398 +0x66\ngithub.com/alecthomas/kingpin.(*Application).Parse(0xc000462000, {0xc00003a130, 0xc000462000, 0x17bd774})\n\t/home/runner/go/pkg/mod/github.com/alecthomas/kingpin@v0.0.0-20200323085623-b6657d9477a6/app.go:230 +0x165\nmain.main()\n\t/home/runner/work/kopia/kopia/main.go:77 +0x310\n"
[33mWARN[0m invalid list cache HMAC for xr, ignoring
[33mWARN[0m invalid list cache HMAC for xe, ignoring
[33mWARN[0m invalid list cache HMAC for xs, ignoring
panic: runtime error: makeslice: len out of range
```

**Comment by jeacott1** [comment]
I just ran into something similar against an azure repo.
```
>kopia snapshot list
ERROR error listing all snapshot manifests: unable to find snapshot manifests: unable to load manifest contents: error loading manifest content: invalid checksum at q92c03e683e13bdc34d295f99580f120a-s865b7f355606422b12b offset 8876 length 512/512: decrypt: unable to decrypt
content: cipher: message authentication failed
```
KOPIA_PASSWORD had not changed and was present as an env var on every run.

before that I was also seeing
```
>kopia snapshot list
WARN invalid list cache HMAC for xr, ignoring
WARN invalid list cache HMAC for xe, ignoring
WARN invalid list cache HMAC for xs, ignoring
ERROR error listing all snapshot manifests: unable to find snapshot manifests: unable to load manifest contents: error loading manifest content: invalid checksum at q4a494a43dfa148dbfbd9464b3bf974b3-s7e5cf84824ac46ab12b offset 32 length 539/539: decrypt: unable to decrypt content: cipher: message authentication failed
```
I was running all this from the docker container, restarted several times without any change, then suddenly it started working again and I have not been able to repeat it. maybe this helps to narrow down a cause.
