### ISSUE TITLE
SIGSEGV: cli.setPolicyFromFlags(0x0, 0xc000369b20, 0x1013c53, 0x16)

### ISSUE THREAD

**Issue by Novex** [kopia/kopia#385]
So I've somehow got kopia into a state where running any `kopia policy set` command results in the following stack trace:

```
[root@ip-172-20-62-250 ~]#  kopia policy set --global --compression zstd
Setting policy for (global)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xd4c076]

goroutine 1 [running]:
github.com/kopia/kopia/cli.setPolicyFromFlags(0x0, 0xc00032db20, 0x1013c53, 0x16)
        /root/kopia/cli/command_policy_set.go:109 +0x26
github.com/kopia/kopia/cli.setPolicy(0x11abe00, 0xc0000a7920, 0xc0002c8f00, 0x1, 0xc0002c8f00)
        /root/kopia/cli/command_policy_set.go:92 +0x272
github.com/kopia/kopia/cli.maybeRepositoryAction.func1.1(0x0, 0x0)
        /root/kopia/cli/app.go:113 +0x148
github.com/kopia/kopia/cli.withProfiling(...)
        /root/kopia/cli/profile_disabled.go:7
github.com/kopia/kopia/cli.maybeRepositoryAction.func1(0xc00015c090, 0x40be03, 0xeb83e0)
        /root/kopia/cli/app.go:92 +0x5d
gopkg.in/alecthomas/kingpin%2ev2.(*actionMixin).applyActions(0xc00034bd58, 0xc00015c090, 0x0, 0x0)
        /root/go/pkg/mod/gopkg.in/alecthomas/kingpin.v2@v2.2.6/actions.go:28 +0x6d
gopkg.in/alecthomas/kingpin%2ev2.(*Application).applyActions(0xc0000e6690, 0xc00015c090, 0x0, 0x0)
        /root/go/pkg/mod/gopkg.in/alecthomas/kingpin.v2@v2.2.6/app.go:557 +0xdc
gopkg.in/alecthomas/kingpin%2ev2.(*Application).execute(0xc0000e6690, 0xc00015c090, 0xc0000b92c0, 0x2, 0x2, 0x0, 0x0, 0x0, 0x28f)
        /root/go/pkg/mod/gopkg.in/alecthomas/kingpin.v2@v2.2.6/app.go:390 +0x8f
gopkg.in/alecthomas/kingpin%2ev2.(*Application).Parse(0xc0000e6690, 0xc0000b0130, 0x5, 0x5, 0x1, 0xc0000af478, 0x0, 0x1)
        /root/go/pkg/mod/gopkg.in/alecthomas/kingpin.v2@v2.2.6/app.go:222 +0x1fe
main.main()
        /root/kopia/main.go:78 +0x178
```

I've tried `kopia cache clear` but it still occurs and it doesn't actually seem to matter what the arguments are (`kopia policy set --global --keep-hourly 0` crashes with the same stack trace).

`kopia policy get` works fine:

```
[root@ip-172-20-62-250 ~]#  kopia policy get --global
Policy for (global):

Retention:
  Annual snapshots:    0           (defined for this target)
  Monthly snapshots:  12           (defined for this target)
  Weekly snapshots:   12           (defined for this target)
  Daily snapshots:    14           (defined for this target)
  Hourly snapshots:    0           (defined for this target)
  Latest snapshots:   10           (defined for this target)

Files policy:
  Ignore rules:
    .snapshot/                     (defined for this target)
    LIBTEST/                       (defined for this target)
    cache.lck                      (defined for this target)
  Read ignore rules from files:
    .kopiaignore                   (defined for this target)

Error handling policy:
  Ignore file read errors:       false       (defined for this target)
  Ignore directory read errors:  false       (defined for this target)

Scheduled snapshots:
  None

Compression:
  Compressor: "zstd" (defined for this target)
  Compress files regardless of extensions.
  Compress files of all sizes.
```

A little more about the environment - I have 19 ec2 instances concurrently migrating backups from an older format to a kopia repository stored on s3. The kopia version is a master built from 2e7fe7c2b3f7f76de30130db3348d26eb68db809.

There is a `kopia policy set` command at the start of the script the instances run to ensure the repository has the correct settings, but possibly running this concurrently has broken things?

**Comment by redgoat650** [comment]
There's a bug here:
```
		p, err := policy.GetDefinedPolicy(ctx, rep, target)
		if err == policy.ErrPolicyNotFound {
			p = &policy.Policy{}
		}
```
Very likely you're hitting an error in `GetDefinedPolicy`, but it isn't `policy.ErrPolicyNotFound`. There isn't any handling for other errors, so the code execution continues with `p == nil`. Fix should be to return any other non-nil errors.

**Comment by jkowalski** [comment]
Can you do 

```
$ kopia policy list
13638add3624f5ed499f668f12225387 (global)
```

Now take the GUID it returns for global and:

```
$ kopia manifest show 13638add3624f5ed499f668f12225387
```

(you will have a different guid in your repository)

**Comment by Novex** [comment]
Ah hmm.. I have four!

```
[root@ip-172-20-38-4 ~]# kopia policy list
0b91a62cc12900daf95c6ed9f7782db3 (global)
cdde44396bec3694be30e47cb893a05d (global)
33272a397c5777d0cf11e4c841079abb (global)
b803edcb88085aa54f215593de10b5bc (global)
```

```
[root@ip-172-20-38-4 ~]# kopia manifest show 0b91a62cc12900daf95c6ed9f7782db3
// id: 0b91a62cc12900daf95c6ed9f7782db3
// length: 329
// modified: 2020-03-23 15:59:44 UTC
// label policyType:global
// label type:policy
{
  "retention": {
    "keepLatest": 10,
    "keepHourly": 0,
    "keepDaily": 14,
    "keepWeekly": 12,
    "keepMonthly": 12,
    "keepAnnual": 0
  },
  "files": {
    "ignore": [
      ".snapshot/",
      "LIBTEST/",
      "cache.lck"
    ],
    "ignoreDotFiles": [
      ".kopiaignore"
    ]
  },
  "errorHandling": {
    "ignoreFileErrors": false,
    "ignoreDirectoryErrors": false
  },
  "scheduling": {},
  "compression": {
    "compressorName": "zstd"
  }
}[root@ip-172-20-38-4 ~]# kopia manifest show cdde44396bec3694be30e47cb893a05d
// id: cdde44396bec3694be30e47cb893a05d
// length: 329
// modified: 2020-03-23 15:59:44 UTC
// label policyType:global
// label type:policy
{
  "retention": {
    "keepLatest": 10,
    "keepHourly": 0,
    "keepDaily": 14,
    "keepWeekly": 12,
    "keepMonthly": 12,
    "keepAnnual": 0
  },
  "files": {
    "ignore": [
      ".snapshot/",
      "LIBTEST/",
      "cache.lck"
    ],
    "ignoreDotFiles": [
      ".kopiaignore"
    ]
  },
  "errorHandling": {
    "ignoreFileErrors": false,
    "ignoreDirectoryErrors": false
  },
  "scheduling": {},
  "compression": {
    "compressorName": "zstd"
  }
}[root@ip-172-20-38-4 ~]# kopia manifest show 33272a397c5777d0cf11e4c841079abb
// id: 33272a397c5777d0cf11e4c841079abb
// length: 329
// modified: 2020-03-23 15:59:45 UTC
// label type:policy
// label policyType:global
{
  "retention": {
    "keepLatest": 10,
    "keepHourly": 0,
    "keepDaily": 14,
    "keepWeekly": 12,
    "keepMonthly": 12,
    "keepAnnual": 0
  },
  "files": {
    "ignore": [
      ".snapshot/",
      "LIBTEST/",
      "cache.lck"
    ],
    "ignoreDotFiles": [
      ".kopiaignore"
    ]
  },
  "errorHandling": {
    "ignoreFileErrors": false,
    "ignoreDirectoryErrors": false
  },
  "scheduling": {},
  "compression": {
    "compressorName": "zstd"
  }
}[root@ip-172-20-38-4 ~]# kopia manifest show b803edcb88085aa54f215593de10b5bc
// id: b803edcb88085aa54f215593de10b5bc
// length: 329
// modified: 2020-03-23 15:59:45 UTC
// label policyType:global
// label type:policy
{
  "retention": {
    "keepLatest": 10,
    "keepHourly": 0,
    "keepDaily": 14,
    "keepWeekly": 12,
    "keepMonthly": 12,
    "keepAnnual": 0
  },
  "files": {
    "ignore": [
      ".snapshot/",
      "LIBTEST/",
      "cache.lck"
    ],
    "ignoreDotFiles": [
      ".kopiaignore"
    ]
  },
  "errorHandling": {
    "ignoreFileErrors": false,
    "ignoreDirectoryErrors": false
  },
  "scheduling": {},
  "compression": {
    "compressorName": "zstd"
  }
}
```

**Comment by jkowalski** [comment]
that's likely the problem

**Comment by jkowalski** [comment]
(the fact that there's four)

**Comment by jkowalski** [comment]
what storage are you using?

**Comment by Novex** [comment]
The s3 backend

**Comment by jkowalski** [comment]
my theory is this has something to do with eventual consistency of S3. If i'm right, it might have fixed itself by now:

Can you also do:

```
$ kopia content list --prefix=m -l
$ kopia manifest list | grep global
$ kopia index list
$ kopia blob list --prefix=q
```

and post here?

**Comment by Novex** [comment]
Unfortunately it hasn't fixed itself - I think it's been about 6 hours since I saw the first case?

```
[root@ip-172-20-38-4 ~]# kopia content list --prefix=m -l
m2154e678892faad88a5ade61aea9300f 2020-03-24 00:46:34 UTC qf5d5797e7e679c75eb42add66154dc2d 58406+479
m30b6232e5667c8601583899f0736073a 2020-03-24 00:44:31 UTC qde8b6e2d062a3b923e5f75f92980681f 716+9760
m3571c6bd06e5e304ab91295be31cb731 2020-03-24 00:45:43 UTC q137188b46901c6fc78df442668ded237 30086+478
m428538d8125f2e0f688cff84095864ee 2020-03-24 01:10:05 UTC q33da65db36b292681d4bb17fd5f8ced5 265363+479
m5ef9f24dd9d6d6dac7d6fd2da6dc5174 2020-03-24 00:47:22 UTC q1f4b82db80d857f95f03df0b4b747441 48433+477
mbd2bc3283055a486a64a04e126fba79f 2020-03-24 00:47:17 UTC qb84a3e7f976cb56d377976197241c6f5 48863+483
md717912c8f3f86f3df975d9236c075b0 2020-03-24 01:26:28 UTC q2a00a5dbce5316cfa9ef2d6a3eceb828 254774+478
mfc9bba781873b6ac21632cc1677bb394 2020-03-24 01:21:00 UTC q3c8a0aba26b891b30a89ebba0eaaac44 222522+475
```

```
[root@ip-172-20-38-4 ~]# kopia manifest list | grep global
0b91a62cc12900daf95c6ed9f7782db3        329 2020-03-23 15:59:44 UTC type:policy policyType:global
cdde44396bec3694be30e47cb893a05d        329 2020-03-23 15:59:44 UTC type:policy policyType:global
33272a397c5777d0cf11e4c841079abb        329 2020-03-23 15:59:45 UTC type:policy policyType:global
b803edcb88085aa54f215593de10b5bc        329 2020-03-23 15:59:45 UTC type:policy policyType:global
```

```
[root@ip-172-20-38-4 ~]# kopia index list
n799ebf7fd075f44c12d453bc8a30a475                                         1356359 2020-03-23 18:08:18.000 UTC
nf8b99ea30469ba8b988b1b6942521238                                         1556067 2020-03-24 00:37:26.000 UTC
nd52f609bdeabf0896963f633f937a0a1                                           18192 2020-03-24 00:39:08.000 UTC
n2c922aa7c4cadeae91a3d80faeb06cb3                                           61243 2020-03-24 00:39:41.000 UTC
n9c9910940ae5f19a066d6f5eca8ab120                                           20790 2020-03-24 00:40:20.000 UTC
n4ea4e00471fc55dda0c034aa19e1db47                                           10594 2020-03-24 00:42:25.000 UTC
n117a8aae6dba2d3f2c230a49bcd836f8                                           27570 2020-03-24 00:42:26.000 UTC
n640e4be6af9e8f74aa92022428c8d577                                           33717 2020-03-24 00:43:12.000 UTC
nffada6754614b8035ff95815fcda7840                                           83474 2020-03-24 00:43:25.000 UTC
nbbbf05743e47b31b3af0de88677d1322                                            1366 2020-03-24 00:44:32.000 UTC
nd78b269c287ebb84b334724538886fe1                                            6791 2020-03-24 00:45:44.000 UTC
nb4dd1db92dd8e6f57c793497261ca77c                                           21033 2020-03-24 00:46:35.000 UTC
n1630245ec248bc9e1dba745e5fd793d7                                            7827 2020-03-24 00:47:19.000 UTC
nbaeba21301180c48b245d579e2acc5e2                                           16050 2020-03-24 00:47:23.000 UTC
nd7360d1448d441dd833a1c1797ed9421                                           24992 2020-03-24 01:10:07.000 UTC
n4b5e1d69747b1da285ff33d79763b98e                                           21625 2020-03-24 01:21:01.000 UTC
n2be6297bb8aaa6b53ccf53cc11a700d8                                           36899 2020-03-24 01:26:29.000 UTC
```

```
[root@ip-172-20-38-4 ~]# kopia blob list --prefix=q
q0076145b56b740ab046ebafd7229efe7                                           79486 2020-03-23 23:59:52 UTC
q03a477a8c8d2d4e333ae54dd53f68764                                            9515 2020-03-24 00:00:33 UTC
q047c45b9aa8778f30efb87bac5b19220                                            4228 2020-03-23 15:59:45 UTC
q05eca9582f8d311bf943698394f84251                                            4228 2020-03-23 15:59:45 UTC
q06273da1272e69bd029d411813abd702                                           25894 2020-03-24 00:00:49 UTC
q077abce9e0df98641037c815678d911b                                          315019 2020-03-23 17:09:28 UTC
q07c03a053e63cbb26eff430c74335b21                                           63313 2020-03-24 00:35:26 UTC
q083a5e99ba6adfc65261743fdbbe1cd7                                           43018 2020-03-24 00:24:25 UTC
q0c97d4b5a10ca04d27ab4736d4bce5fb                                           88296 2020-03-23 15:45:45 UTC
q0d648b09fd4c4f4a26faebe703c9e0a9                                           34308 2020-03-24 00:43:12 UTC
q137188b46901c6fc78df442668ded237                                           34271 2020-03-24 00:45:44 UTC
q1ebd49c83c4a20994e9e2b6ef23e6a05                                          174867 2020-03-23 16:09:23 UTC
q1f4b82db80d857f95f03df0b4b747441                                           50877 2020-03-24 00:47:23 UTC
q2156c92c6092d51c99750e918de4f8a7                                           29990 2020-03-24 00:01:18 UTC
q24d5cf4b3df353cbf2ce67c02f162016                                           72689 2020-03-24 00:08:05 UTC
q252185465ad9423bd14adaad0735d4f8                                          175237 2020-03-23 13:57:31 UTC
q2a00a5dbce5316cfa9ef2d6a3eceb828                                          261179 2020-03-24 01:26:29 UTC
q2d08e6891fd55b7e5c7d33040d880a88                                          167045 2020-03-23 20:34:35 UTC
q33da65db36b292681d4bb17fd5f8ced5                                          270185 2020-03-24 01:10:06 UTC
q341642314c9685d58c6b31b3f69d3b69                                          104717 2020-03-24 00:01:04 UTC
q36f5efb430f21964f0dcf1e4106be65c                                           25894 2020-03-23 23:59:39 UTC
q3b8be00746b6beb338b1c02ad3980b81                                          137855 2020-03-23 16:07:58 UTC
q3c3f4689cb02451582f83bb68d5d6641                                          104643 2020-03-24 00:31:42 UTC
q3c8a0aba26b891b30a89ebba0eaaac44                                          228263 2020-03-24 01:21:01 UTC
q3c935cbcad7dfb95d4f3a9553698f8c1                                          188450 2020-03-24 00:40:20 UTC
q400a626e0ee493aaaa89eb533a90be8b                                            4228 2020-03-23 13:14:56 UTC
q460a140a286d8804bbf4eee89865f49a                                            5419 2020-03-23 16:02:00 UTC
q47047bb55d527c6ca2d16627df66deea                                          113427 2020-03-23 16:51:41 UTC
q4780258884f9a8702c7a180c67640ca2                                         4400545 2020-03-24 00:08:25 UTC
q5131b5eac9be2a4dfd96526524da7a61                                            4228 2020-03-23 15:42:33 UTC
q51dffc3ef8cf296b703dcf756e40903c                                           25894 2020-03-23 23:59:38 UTC
q55ce3c6dabdaa9dd1b24874035fbd51f                                           35233 2020-03-23 13:51:45 UTC
q563ef0deb542dbc4192cf93777dcbcc7                                           76082 2020-03-23 16:15:25 UTC
q5e6cfc2af559ef43ccd5a022b3eebb86                                          327899 2020-03-23 16:52:37 UTC
q5f3b80b6d8ec70e29f9eaa074c05c491                                          170845 2020-03-23 16:15:25 UTC
q603d8e3ae109c9c965160c425e4e1c93                                          125493 2020-03-23 16:14:36 UTC
q639602ed83c931a1fe6be528dd18a8c8                                         1432657 2020-03-24 00:18:59 UTC
q640795c9732282134c7226f17114c073                                           34382 2020-03-24 00:12:55 UTC
q65c341b6ba24564183d03ade9e10bcf1                                          367897 2020-03-23 18:13:33 UTC
q6bfa39f940295521865d241119aa20e1                                          126011 2020-03-23 17:10:59 UTC
q6e7287e3009018cf95964bbafe4a3354                                           51099 2020-03-24 00:28:40 UTC
q6fe08893be27370575bcb3b45a795b8e                                            9445 2020-03-23 17:06:14 UTC
q77c76927461be395d8706b896d0553b8                                           63239 2020-03-24 00:10:11 UTC
q79b8060e9587f4e080cdc1ba00a7c13a                                           92910 2020-03-23 16:01:46 UTC
q7a7f541a86d772b3866c424edc24befb                                           75712 2020-03-24 00:42:25 UTC
q83b6f3b0c4fbf3343095aba6c9d754a3                                          121582 2020-03-23 16:06:01 UTC
q86fb9ca12c2bce6f4f93903bfca1d34d                                           38441 2020-03-24 00:04:44 UTC
q8cbd4aa8f7210dac357463999c331fd6                                            4228 2020-03-23 15:59:46 UTC
q8dd574174ae7f039e53c43caffb793c8                                          386205 2020-03-23 18:01:37 UTC
q8f58793a547bd7e51157b5eb6df9725b                                           30101 2020-03-23 23:59:44 UTC
q91e7d5a47e63017b3e6264cf5039a901                                           46670 2020-03-24 00:02:58 UTC
q9629f14b466127445f39a772b087e031                                           55084 2020-03-24 00:39:08 UTC
qa483a317c87075042c20045abd0919d8                                          104717 2020-03-23 16:08:31 UTC
qa5106482e0a8f99fe27908eee6d687d4                                           38478 2020-03-24 00:02:00 UTC
qa56467806266bc993fe58b1fd9fd0ced                                           34308 2020-03-24 00:01:58 UTC
qa6fc0e65748eabbf3a613771c3e4ecdb                                           46707 2020-03-24 00:01:43 UTC
qa8898a356439b88ce575f26f57341eda                                          325024 2020-03-23 20:23:32 UTC
qa8a3b39bbfe5f9bc299c6c2119fbebb9                                           38478 2020-03-24 00:02:26 UTC
qa9c639ada33fcf54a6d5932ae9c63162                                           47706 2020-03-24 00:19:48 UTC
qab6a9f6f3cfec207a43f80dffa3098b9                                          109146 2020-03-23 16:12:25 UTC
qac10c51e23e753234a2b13098f541764                                           30027 2020-03-23 13:56:00 UTC
qacd92d75f050bf398c4d216fdfe233cf                                           30175 2020-03-24 00:03:26 UTC
qaf3bfbe5703fd2d2060b2064552329cc                                          117338 2020-03-23 14:00:56 UTC
qb0c3191612144f1a59745f8d8372a95f                                          172140 2020-03-24 00:34:12 UTC
qb280445cb30f10d0d88be2368b703a34                                          268901 2020-03-24 00:36:45 UTC
qb40490e1ac338c15bb44862247d8af52                                            4228 2020-03-23 15:59:46 UTC
qb7b6326759f94ac192db6d144a9dab8c                                          125789 2020-03-23 16:59:45 UTC
qb84a3e7f976cb56d377976197241c6f5                                           55047 2020-03-24 00:47:18 UTC
qbe19138cb9a340aa31ca84788a928c37                                           88259 2020-03-23 16:02:14 UTC
qbe6d58652c274293b7cf657f5b6c309e                                           84311 2020-03-23 16:16:10 UTC
qbf3f0ce1fcaf70024516434df02bef8b                                          203687 2020-03-24 01:33:54 UTC
qbf98540ad88295978e78a7e65e3cc5ac                                          198518 2020-03-24 00:42:26 UTC
qc89278af5dab048903472f8a9770624e                                            4228 2020-03-23 15:59:44 UTC
qcf2ddb7dd45afe8a41acc287b4c2c39c                                            8732 2020-03-23 15:37:21 UTC
qd1ad2c2f19314650807d3b33d38d8844                                           13541 2020-03-24 00:09:23 UTC
qd356e0df29c66d0157934a38e6ea7e60                                          129663 2020-03-24 00:02:13 UTC
qd54711689e566d176c6534ffd287b8c6                                           25894 2020-03-24 00:00:03 UTC
qd851109fa944a466d55a542e4f1b0ab0                                           25894 2020-03-23 23:59:46 UTC
qdcaa54a9e827a2d0df5b46eb07d1d45c                                           96007 2020-03-24 00:39:41 UTC
qde113cb6ee6059875f53d381dee092b9                                           30175 2020-03-24 00:00:46 UTC
qde8b6e2d062a3b923e5f75f92980681f                                           13681 2020-03-24 00:44:32 UTC
qdf623c598a9cba515a3bf478fab2e0ff                                          277563 2020-03-23 17:16:59 UTC
qe6d96212a91dcd5871f9dc309716320a                                           30101 2020-03-23 23:59:45 UTC
qe82a33d52c564006273aa49cb9333b2d                                          231286 2020-03-23 17:21:26 UTC
qf139e5b50add7f1036a9c8de4e3dc154                                           30101 2020-03-24 00:07:25 UTC
qf4c23d22eb097c5c52f5aec0ec1319e4                                           92392 2020-03-23 16:01:46 UTC
qf509925113db4109c82238549e7d8cef                                           34419 2020-03-24 00:43:24 UTC
qf585508655d17a76adc758edbbdcf9e4                                          113094 2020-03-23 13:59:04 UTC
qf5d5797e7e679c75eb42add66154dc2d                                           63498 2020-03-24 00:46:35 UTC
qfa25fd81dee149f4c8561dd22c5ada84                                           96673 2020-03-23 16:17:36 UTC
qfbc996558683a354a80f186427f9ed5b                                            4228 2020-03-23 13:14:55 UTC
qfd62965ca911f604a064c6ea4d365257                                          493478 2020-03-23 22:39:24 UTC
qfebb596caff09e365c86c3fbaaf00c28                                          121323 2020-03-23 16:04:55 UTC
```

**Comment by jkowalski** [comment]
Hmm, want to jump on slack so we can have interactive debugging? slack.kopia.io ?

**Comment by jkowalski** [comment]
also, can you confirm that your system time is reasonably ok, within <1m of the official time?

**Comment by jkowalski** [comment]
what bothers me that is there is no `m` content around the same time as when the policy was set, 

can you also do `kopia content show m30b6232e5667c8601583899f0736073a | gzip -d` ?

**Comment by Novex** [comment]
Yep, give me a tic I'll jump on slack. System time is ok and when I tried the `kopia content show` it said content not found. 

listing the content again shows that it's changed (the nodes are still uploading snapshots at the moment)
```
[root@ip-172-20-38-4 ~]# kopia content list --prefix=m -l
m059a40f05d3ddd673ef84bb614eb62f5 2020-03-24 02:24:11 UTC q626727800ce720f54a2895baeb1411be 68414+520
m186741c654a2c19a36b24ff2c9002006 2020-03-24 03:01:20 UTC q6a9dfdea0c1b9514713308326fecfb94 181746+478
m1fecc3896ff17d8d34e3a6fac8ca6513 2020-03-24 03:37:20 UTC q9d4768fd7c5628cd0979bff6bca35e74 230290+487
m3432ed7cc6b8f2a7a92b118c2f5f3243 2020-03-24 03:47:14 UTC q4c10583fc8a8aff45fc313997132c9e2 527669+478
m7a5d3e1c7cf4fab92e481fcea8ac7a21 2020-03-24 02:26:47 UTC q43119e8b6af780c99352f749cd727a6e 29106+478
m9caf877f088de95a798c814dccd139f2 2020-03-24 02:51:15 UTC qc33b895a4ad6fd29f11f26262de79864 265674+479
mc35a0ef02f630d50e48693ca8a9abac8 2020-03-24 03:04:36 UTC qf20c15189e856a4490dc5c9b764453e4 56207+487
md922b6566ff4d842b87a141d15e65cd2 2020-03-24 02:21:35 UTC q78e8fa53270672f1fa50632ca0cef1c4 716+11677
me1c214a758806e4d301dfbfe364db7d4 2020-03-24 03:09:22 UTC q37da86ddeacd5a405d23f38dd4eff2a7 199607+483
mf95a0484dfce0cfbd85e59a96e64c7a1 2020-03-24 02:59:28 UTC q8c47b580b2c3c29a01cb68e5b41d678e 225422+482
```

**Comment by Novex** [comment]
So the result of the slack discussion is that this is caused by two processes concurrently trying to set the policy. They create more than one manifest which is ambiguous since kopia doesn't know which holds the correct policy.

After compiling 393d273e5af8d74fac00a15cc32f76836285b8dd and running the same commands the stack trace is replaced by an error message:

```
[root@ip-172-20-38-4 kopia]# ~/go/bin/kopia policy set --global --compression zstd
kopia: error: could not get defined policy: ambiguous policy, try --help
```

If anyone else has this issue, use  `kopia manifest list | grep 'policyType:global'` to find the ID's for the extra manifests

```
[root@ip-172-20-38-4 kopia]# kopia manifest list | grep 'policyType:global'
0b91a62cc12900daf95c6ed9f7782db3        329 2020-03-23 15:59:44 UTC type:policy policyType:global
cdde44396bec3694be30e47cb893a05d        329 2020-03-23 15:59:44 UTC type:policy policyType:global
33272a397c5777d0cf11e4c841079abb        329 2020-03-23 15:59:45 UTC type:policy policyType:global
b803edcb88085aa54f215593de10b5bc        329 2020-03-23 15:59:45 UTC type:policy policyType:global
```

and then use `kopia manifest rm` to remove all but one manifest should allow you to set policy again

```
[root@ip-172-20-38-4 kopia]# kopia manifest rm 0b91a62cc12900daf95c6ed9f7782db3 cdde44396bec3694be30e47cb893a05d 33272a397c5777d0cf11e4c841079
[root@ip-172-20-38-4 kopia]# ~/go/bin/kopia policy set --global --compression zstd
Setting policy for (global)
 - setting compression algorithm to zstd
```

**Comment by jkowalski** [comment]
for posterity - we understand the issue now, the race where we create multiple manifests is unavoidable with the kind of backend we have to work with. we need to resolve this race on read in manifest manager.
