### ISSUE TITLE
panic: runtime error: makeslice: len out of range

### ISSUE THREAD

**Issue by MrTalon63** [kopia/kopia#3857]
When I tried to restore my snapshot the UI just says Network Error, while CLI shows `panic: runtime error: makeslice: len out of range` with this error log
```
goroutine 1 [running]:
github.com/kopia/kopia/internal/epoch.(*Manager).getCompleteIndexSetForCommittedState(0xc0000a7c20, {0x1a80b60, 0xc000018330}, {0x0, 0xc00579ee40, {0xc000351170, 0x5, 0x6}, 0xc00027f8c0, 0xc00027f860, ...}, ...)
        D:/a/kopia/kopia/internal/epoch/epoch_manager.go:995 +0x357
github.com/kopia/kopia/internal/epoch.(*Manager).GetCompleteIndexSet(0xc0000a7c20, {0x1a80b60, 0xc000018330}, 0x1?)
        D:/a/kopia/kopia/internal/epoch/epoch_manager.go:834 +0x1b5
github.com/kopia/kopia/repo/content/indexblob.(*ManagerV1).ListActiveIndexBlobs(0xc00009ea80, {0x1a80b60?, 0xc000018330?})
        D:/a/kopia/kopia/repo/content/indexblob/index_blob_manager_v1.go:39 +0x48
github.com/kopia/kopia/repo/content.(*SharedManager).loadPackIndexesLocked(0xc000236000, {0x1a80b60, 0xc000018330})
        D:/a/kopia/kopia/repo/content/committed_read_manager.go:228 +0x275
github.com/kopia/kopia/repo/content.NewSharedManager({0x1a80b60, 0xc000018330}, {0x1a8bb88, 0xc000019b60}, {0x1a8ba98, 0xc0001b7a00}, 0xc00030d2d8, 0x0?, 0xc000019bc0, 0xc0004305c0)
        D:/a/kopia/kopia/repo/content/committed_read_manager.go:646 +0x585
github.com/kopia/kopia/repo.openWithConfig({0x1a80b60, 0xc000018330}, {0x1a8bc00, 0xc000018b10}, {{0xc000137dbe, 0x2}, {0xc000137e30, 0x5}, 0x0, 0x0, ...}, ...)
        D:/a/kopia/kopia/repo/open.go:326 +0xaee
github.com/kopia/kopia/repo.openDirect({0x1a80b60, 0xc000018330}, {0xc00010b400, 0x36}, 0xc000162150, {0xc000134620, 0x20}, 0xc00063f8e0)
        D:/a/kopia/kopia/repo/open.go:226 +0x334
github.com/kopia/kopia/repo.Open({0x1a80b60?, 0xc000018210?}, {0xc000106600, 0x36}, {0xc000134620, 0x20}, 0xc00063f8e0)
        D:/a/kopia/kopia/repo/open.go:131 +0x43d
github.com/kopia/kopia/cli.(*App).openRepository(0xc0001d8008, {0x1a80b60, 0xc000018210}, 0x1)
        D:/a/kopia/kopia/cli/config.go:67 +0x238
github.com/kopia/kopia/cli.(*App).repositoryReaderAction.(*App).maybeRepositoryAction.func2({0x1a80b60, 0xc000018210})
        D:/a/kopia/kopia/cli/app.go:538 +0x5b
github.com/kopia/kopia/cli.(*App).repositoryReaderAction.(*App).maybeRepositoryAction.(*App).baseActionWithContext.func3.1.1()
        D:/a/kopia/kopia/cli/app.go:530 +0x7d
github.com/kopia/kopia/cli.(*profileFlags).withProfiling(0x0?, 0x0?)
        D:/a/kopia/kopia/cli/profile.go:45 +0x345
github.com/kopia/kopia/cli.(*App).repositoryReaderAction.(*App).maybeRepositoryAction.(*App).baseActionWithContext.func3.1({0x1a80b60?, 0xc000018210?})
        D:/a/kopia/kopia/cli/app.go:525 +0x65
github.com/kopia/kopia/cli.(*App).runAppWithContext.func1({0x1a80b60, 0xc0000181e0}, 0xc0000181e0?, 0xc0001d8008, 0xc00063fd30)
        D:/a/kopia/kopia/cli/app.go:496 +0x183
github.com/kopia/kopia/cli.(*App).runAppWithContext(0xc0001d8008, 0xc0000ed5f0, 0xc00063fd30)
        D:/a/kopia/kopia/cli/app.go:497 +0x1a9
github.com/kopia/kopia/cli.(*App).repositoryReaderAction.(*App).maybeRepositoryAction.(*App).baseActionWithContext.func3(0x1a6b101?)
        D:/a/kopia/kopia/cli/app.go:524 +0x4b
github.com/alecthomas/kingpin/v2.(*actionMixin).applyActions(...)
        C:/Users/runneradmin/go/pkg/mod/github.com/alecthomas/kingpin/v2@v2.4.0/actions.go:28
github.com/alecthomas/kingpin/v2.(*Application).applyActions(0xc0001b6600?, 0xc0001a7170)
        C:/Users/runneradmin/go/pkg/mod/github.com/alecthomas/kingpin/v2@v2.4.0/app.go:568 +0xd0
github.com/alecthomas/kingpin/v2.(*Application).execute(0xc0001b6600, 0xc0001a7170, {0xc000094f80, 0x2, 0x2})
        C:/Users/runneradmin/go/pkg/mod/github.com/alecthomas/kingpin/v2@v2.4.0/app.go:398 +0x65
github.com/alecthomas/kingpin/v2.(*Application).Parse(0xc0001b6600, {0xc00012c0d0?, 0xc0001b6600?, 0x1a6b0c0?})
        C:/Users/runneradmin/go/pkg/mod/github.com/alecthomas/kingpin/v2@v2.4.0/app.go:230 +0x14a
main.main()
        D:/a/kopia/kopia/main.go:77 +0x1cc
```

**Comment by julio-lopez** [comment]
@MrTalon63 version?

**Comment by MrTalon63** [comment]
> @MrTalon63 version?

Both 0.15.0 and 0.17.0

**Comment by fresh2dev** [comment]
I'm getting this, too, running running v0.18.2 in Kubernetes. I was previous backing up to disk fronted by an SFTP server. I since rearranged my cluster and am trying to backup to a local disk (mounted NFS share). After entering the repository password, the pod repeatedly crashes with this error.

```
panic: runtime error: makeslice: len out of range

goroutine 9 [running]:
github.com/kopia/kopia/internal/epoch.(*Manager).getCompleteIndexSetForCommittedState(0xc0006f2f00, {0x25bbbb8, 0xc0000b7380}, {0x0, 0xc0054419b0, {0xc005416c00, 0x7, 0x8}, 0xc0000be960, 0xc0000be900, ...}, ...)
    /home/runner/work/kopia/kopia/internal/epoch/epoch_manager.go:920 +0x357
github.com/kopia/kopia/internal/epoch.(*Manager).GetCompleteIndexSet(0xc0006f2f00, {0x25bbbb8, 0xc0000b7380}, 0x1?)
    /home/runner/work/kopia/kopia/internal/epoch/epoch_manager.go:759 +0x1d5
github.com/kopia/kopia/repo/content/indexblob.(*ManagerV1).ListActiveIndexBlobs(0xc00090e780, {0x25bbbb8?, 0xc0000b7380?})
    /home/runner/work/kopia/kopia/repo/content/indexblob/index_blob_manager_v1.go:39 +0x48
github.com/kopia/kopia/repo/content.(*SharedManager).loadPackIndexesLocked(0xc00086f500, {0x25bbbb8, 0xc0000b7380})
    /home/runner/work/kopia/kopia/repo/content/committed_read_manager.go:229 +0x275
github.com/kopia/kopia/repo/content.NewSharedManager({0x25bbbb8, 0xc0000b7380}, {0x25c8558, 0xc0001d8ff0}, {0x25c8468, 0xc0006f2500}, 0xc0001ed798, 0x0?, 0xc0001d9050, 0xc00087b580)
    /home/runner/work/kopia/kopia/repo/content/committed_read_manager.go:647 +0x585
github.com/kopia/kopia/repo.openWithConfig({0x25bbbb8, 0xc0000b7380}, {0x25c85d0, 0xc0000b7bc0}, {{0xc0009a3ba8, 0x7}, {0xc0009a3bb0, 0x4}, 0x0, 0x0, ...}, ...)
    /home/runner/work/kopia/kopia/repo/open.go:329 +0xaee
github.com/kopia/kopia/repo.openDirect({0x25bbbb8, 0xc0000b7380}, {0xc00005e012, 0x1d}, 0xc000a7cfc0, {0xc00005a06f, 0xc}, 0xc0001c5da8)
    /home/runner/work/kopia/kopia/repo/open.go:229 +0x334
github.com/kopia/kopia/repo.Open({0x25bbbf0?, 0xc0009a4410?}, {0xc00005e012, 0x1d}, {0xc00005a06f, 0xc}, 0xc000191da8)
    /home/runner/work/kopia/kopia/repo/open.go:131 +0x43d
github.com/kopia/kopia/cli.(*App).openRepository(0xc000ac2008, {0x25bbbf0, 0xc0009a4410}, 0x0)
    /home/runner/work/kopia/kopia/cli/config.go:67 +0x268
github.com/kopia/kopia/cli.(*commandServerStart).initRepositoryPossiblyAsync.func1({0x25bbbf0?, 0xc0009a4410?})
    /home/runner/work/kopia/kopia/cli/command_server_start.go:172 +0x3e
github.com/kopia/kopia/internal/server.(*Server).InitRepositoryAsync.func1({0x25bbbb8, 0xc0000b72c0}, {0x25bc6c8, 0xc000015260})
    /home/runner/work/kopia/kopia/internal/server/server.go:868 +0x1a6
github.com/kopia/kopia/internal/uitask.(*Manager).Run(0xc00087b380, {0x25bbbb8, 0xc0000b7170}, {0x1e2d161, 0xa}, {0x1e24b9b, 0x4}, 0xc0000b7260)
    /home/runner/work/kopia/kopia/internal/uitask/uitask_manager.go:71 +0x20f
created by github.com/kopia/kopia/internal/server.(*Server).InitRepositoryAsync in goroutine 1
    /home/runner/work/kopia/kopia/internal/server/server.go:852 +0x1e5
stream closed EOF for default/kopia-0 (kopia)
```

**Comment by fresh2dev** [comment]
This even happens when using the Kopia v0.19.0 CLI 😩 

```
~$ kopia repository connect filesystem --path /mnt/backup/backups/kopia
Enter password to open repository:

panic: runtime error: makeslice: len out of range

goroutine 1 [running]:
github.com/kopia/kopia/internal/epoch.(*Manager).getCompleteIndexSetForCommittedState(0xc00058bb00, {0x2641078, 0xc000514090}, {0x0, 0xc005283ad0, {0xc000619a00, 0x7, 0x8}, 0xc000317a10, 0xc0003179b0, ...}, ...)
        /home/runner/work/kopia/kopia/internal/epoch/epoch_manager.go:920 +0x357
github.com/kopia/kopia/internal/epoch.(*Manager).GetCompleteIndexSet(0xc00058bb00, {0x2641078, 0xc000514090}, 0x4?)
        /home/runner/work/kopia/kopia/internal/epoch/epoch_manager.go:759 +0x1d5
github.com/kopia/kopia/repo/content/indexblob.(*ManagerV1).ListActiveIndexBlobs(0xc000619500, {0x2641078?, 0xc000514090?})
        /home/runner/work/kopia/kopia/repo/content/indexblob/index_blob_manager_v1.go:39 +0x48
github.com/kopia/kopia/repo/content.(*SharedManager).loadPackIndexesLocked(0xc000546000, {0x2641078, 0xc000514090})
        /home/runner/work/kopia/kopia/repo/content/committed_read_manager.go:229 +0x275
github.com/kopia/kopia/repo/content.NewSharedManager({0x2641078, 0xc000514090}, {0x264e258, 0xc000515350}, {0x264e168, 0xc00058b700}, 0xc00052f100, 0x0?, 0xc0005153b0, 0xc000069d00)
        /home/runner/work/kopia/kopia/repo/content/committed_read_manager.go:647 +0x585
github.com/kopia/kopia/repo.openWithConfig({0x2641078, 0xc000514090}, {0x264e7f8, 0xc00048ab40}, {{0xc00047e768, 0x11}, {0xc000012348, 0x4}, 0x0, 0x0, ...}, ...)
        /home/runner/work/kopia/kopia/repo/open.go:329 +0xb49
github.com/kopia/kopia/repo.openDirect({0x2641078, 0xc000514090}, {0xc00016a000, 0x25}, 0xc0002402a0, {0xc000502010, 0xc}, 0xc00039f5f0)
        /home/runner/work/kopia/kopia/repo/open.go:229 +0x334
github.com/kopia/kopia/repo.Open({0x2641078?, 0xc00025d6b0?}, {0xc00016a000, 0x25}, {0xc000502010, 0xc}, 0x0)
        /home/runner/work/kopia/kopia/repo/open.go:131 +0x43d
github.com/kopia/kopia/repo.verifyConnect({0x2641078, 0xc00025d6b0}, {0xc00016a000, 0x25}, {0xc000502010?, 0xc0000ba4c0?})
        /home/runner/work/kopia/kopia/repo/connect.go:69 +0x47
github.com/kopia/kopia/repo.Connect({0x2641078, 0xc00025d6b0}, {0xc00016a000, 0x25}, {0x264e7f8, 0xc00061e420}, {0xc000502010, 0xc}, 0xc00008e048?)
        /home/runner/work/kopia/kopia/repo/connect.go:64 +0x4d8
github.com/kopia/kopia/cli.(*App).runConnectCommandWithStorageAndPassword(0xc00059e808, {0x2641078, 0xc00025d6b0}, 0xc0005a0598, {0x264e7f8, 0xc00061e420}, {0xc000502010, 0xc})
        /home/runner/work/kopia/kopia/cli/command_repository_connect.go:129 +0xb5
github.com/kopia/kopia/cli.(*App).runConnectCommandWithStorage(0xc00059e808, {0x2641078, 0xc00025d6b0}, 0xc0005a0598, {0x264e7f8, 0xc00061e420})
        /home/runner/work/kopia/kopia/cli/command_repository_connect.go:123 +0x85
github.com/kopia/kopia/cli.(*commandRepositoryConnect).setup.func1.1({0x2641078, 0xc00025d6b0})
        /home/runner/work/kopia/kopia/cli/command_repository_connect.go:40 +0x9f
github.com/kopia/kopia/cli.(*App).runAppWithContext.func1(0xc00059e8d0?, 0xc00059e808, 0xc00025d5f0, {0x2641078, 0xc00025d650})
        /home/runner/work/kopia/kopia/cli/app.go:530 +0x1a3
github.com/kopia/kopia/cli.(*App).runAppWithContext(0xc00059e808, 0xc000136820, 0xc00025d5f0)
        /home/runner/work/kopia/kopia/cli/app.go:531 +0x1a9
github.com/kopia/kopia/cli.(*commandRepositoryConnect).setup.func1(0xc00061d560)
        /home/runner/work/kopia/kopia/cli/command_repository_connect.go:34 +0xcb
github.com/alecthomas/kingpin/v2.(*actionMixin).applyActions(...)
        /home/runner/go/pkg/mod/github.com/alecthomas/kingpin/v2@v2.4.0/actions.go:28
github.com/alecthomas/kingpin/v2.(*Application).applyActions(0xc00058a400?, 0xc00061d560)
        /home/runner/go/pkg/mod/github.com/alecthomas/kingpin/v2@v2.4.0/app.go:568 +0xd0
github.com/alecthomas/kingpin/v2.(*Application).execute(0xc00058a400, 0xc00061d560, {0xc00048c700, 0x3, 0x4})
        /home/runner/go/pkg/mod/github.com/alecthomas/kingpin/v2@v2.4.0/app.go:398 +0x65
github.com/alecthomas/kingpin/v2.(*Application).Parse(0xc00058a400, {0xc0000501f0?, 0xc00058a400?, 0x26141a0?})
        /home/runner/go/pkg/mod/github.com/alecthomas/kingpin/v2@v2.4.0/app.go:230 +0x14a
main.main()
        /home/runner/work/kopia/kopia/main.go:77 +0x1cc
```

**Comment by julio-lopez** [comment]
Are there messages in the logs with the following text: ` adding incremental state for epochs ` ?
Can you share those messages?
