### ISSUE TITLE
"panic: runtime error: makeslice: len out of range" during maintenance

### ISSUE THREAD

**Issue by faevourite** [kopia/kopia#4000]
Seeing this once in a while in Kopia UI logs on an M2 Mac around maintenance completion. kopia 0.17.0, rclone v1.67.0 with a GDrive storage backend.

```
...
[info]  Finished full maintenance.

[info]  panic: runtime error: makeslice: len out of range

goroutine 541 [running]:

[2024-07-09 14:46:41.817] [info]  github.com/kopia/kopia/internal/epoch.(*Manager).getCompleteIndexSetForCommittedState(0x1400073c240, {0x105a4f360, 0x14005637800}, {0x0, 0x1401327e9c0, {0x1400561b5d0, 0x1, 0x1}, 0x14012de5b90, 0x14012de5b30, ...}, ...)
	/Users/runner/work/kopia/kopia/internal/epoch/epoch_manager.go:995 +0x2c8
github.com/kopia/kopia/internal/epoch.(*Manager).GetCompleteIndexSet(0x1400073c240, {0x105a4f360, 0x14005637800}, 0x14005637801?)
	/Users/runner/work/kopia/kopia/internal/epoch/epoch_manager.go:834 +0x10c
github.com/kopia/kopia/repo/content/indexblob.(*ManagerV1).ListActiveIndexBlobs(0x140051ff480, {0x105a4f360?, 0x14005637800?})
	/Users/runner/work/kopia/kopia/repo/content/indexblob/index_blob_manager_v1.go:39 +0x3c
github.com/kopia/kopia/repo/content.(*SharedManager).loadPackIndexesLocked(0x140001e4d80, {0x105a4f360, 0x14005637800})
	/Users/runner/work/kopia/kopia/repo/content/committed_read_manager.go:228 +0x1c4
github.com/kopia/kopia/repo/content.(*SharedManager).CompactIndexes(0x140001e4d80, {0x105a4f360, 0x14005637800}, {0x0, 0x1, {0xc4ae578, 0xede1a0ae5, 0x106429c00}, {0x0, 0x0, ...}, ...})
	/Users/runner/work/kopia/kopia/repo/content/content_manager_indexes.go:57 +0x154
github.com/kopia/kopia/repo/maintenance.DropDeletedContents({0x105a4f360, 0x14005637800}, {0x105a621d8, 0x1400118a6e0}, {0xc4ae578, 0xede1a0ae5, 0x106429c00}, {0x68c61714000, 0x4e94914f0000, 0xd18c2e28000, ...})
	/Users/runner/work/kopia/kopia/repo/maintenance/drop_deleted_contents.go:16 +0x130
github.com/kopia/kopia/repo/maintenance.runTaskDropDeletedContentsFull.func1()
	/Users/runner/work/kopia/kopia/repo/maintenance/maintenance_run.go:431 +0x60
github.com/kopia/kopia/repo/maintenance.ReportRun({0x105a4f360, 0x14005637800}, {0x105a621d8, 0x1400118a6e0}, {0x104f8f654, 0x19}, 0x1?, 0x140053cf5b8)
	/Users/runner/work/kopia/kopia/repo/maintenance/maintenance_schedule.go:197 +0x9c
github.com/kopia/kopia/repo/maintenance.runTaskDropDeletedContentsFull({0x105a4f360, 0x14005637800}, {{0x105a621d8, 0x1400118a6e0}, {0x104f6dd85, 0x4}, 0x140005e9da0, {0x0, 0xede1f7bd0, 0x140076d2f50}}, ...)
	/Users/runner/work/kopia/kopia/repo/maintenance/maintenance_run.go:430 +0x260
github.com/kopia/kopia/repo/maintenance.runFullMaintenance({0x105a4f360, 0x14005637800}, {{0x105a621d8, 0x1400118a6e0}, {0x104f6dd85, 0x4}, 0x140005e9da0, {0x0, 0xede1f7bd0, 0x140076d2f50}}, ...)
	/Users/runner/work/kopia/kopia/repo/maintenance/maintenance_run.go:500 +0x174
github.com/kopia/kopia/repo/maintenance.Run({0x105a4f360?, 0x14005637800?}, {{0x105a621d8, 0x1400118a6e0}, {0x104f6dd85, 0x4}, 0x140005e9da0, {0x0, 0xede1f7bd0, 0x140076d2f50}}, ...)
	/Users/runner/work/kopia/kopia/repo/maintenance/maintenance_run.go:247 +0x94
github.com/kopia/kopia/internal/server.(*Server).runMaintenanceTask.func1.1.Run.1({0x105a4f360?, 0x14005637800?}, {{0x105a621d8, 0x1400118a6e0}, {0x104f6dd85, 0x4}, 0x140005e9da0, {0x0, 0xede1f7bd0, 0x140076d2f50}})
	/Users/runner/work/kopia/kopia/snapshot/snapshotmaintenance/snapshotmaintenance.go:27 +0x13c
github.com/kopia/kopia/repo/maintenance.RunExclusive({0x105a4f360, 0x14005637650}, {0x105a621d8, 0x1400118a6e0}, {0x104f6de2d, 0x4}, 0x0, 0x1400004dc20)
	/Users/runner/work/kopia/kopia/repo/maintenance/maintenance_run.go:221 +0x650

[info]  github.com/kopia/kopia/snapshot/snapshotmaintenance.Run(...)
	/Users/runner/work/kopia/kopia/snapshot/snapshotmaintenance/snapshotmaintenance.go:17
github.com/kopia/kopia/internal/server.(*Server).runMaintenanceTask.func1.1({0x105a4f360?, 0x14005637650?}, {0x105a621d8?, 0x1400118a6e0?})
	/Users/runner/work/kopia/kopia/internal/server/server.go:972 +0xd4
github.com/kopia/kopia/repo.DirectWriteSession({0x105a4f360, 0x14005637620}, {0x105a60768, 0x1400017fa20}, {{0x104f834f9?, 0x105746ca0?}, 0x30?, 0x0?}, 0x105a37138)
	/Users/runner/work/kopia/kopia/repo/repository.go:415 +0x128
github.com/kopia/kopia/internal/server.(*Server).runMaintenanceTask.func1({0x105a4f360?, 0x14005637620?}, {0x140056446e0?, 0x0?})
	/Users/runner/work/kopia/kopia/internal/server/server.go:969 +0x48
github.com/kopia/kopia/internal/uitask.(*Manager).Run(0x140000caf80, {0x105a4f398, 0x14000220640}, {0x104f76d04, 0xb}, {0x104f8541d, 0x14}, 0x140003cee80)
	/Users/runner/work/kopia/kopia/internal/uitask/uitask_manager.go:71 +0x1e4
github.com/kopia/kopia/internal/server.(*Server).runMaintenanceTask(0x105a4f360?, {0x105a4f398?, 0x14000220640?}, {0x105a60768?, 0x1400017fa20?})
	/Users/runner/work/kopia/kopia/internal/server/server.go:968 +0x68
github.com/kopia/kopia/internal/server.startMaintenanceManager.func1()
	/Users/runner/work/kopia/kopia/internal/server/server_maintenance.go:141 +0x15c
created by github.com/kopia/kopia/internal/server.startMaintenanceManager in goroutine 15
	/Users/runner/work/kopia/kopia/internal/server/server_maintenance.go:131 +0x220

[info]  child process exited with code 2 and signal null
```

It seems to auto-recover on the next full maintenance. Doesn't prevent further snapshots or restores.

**Comment by julio-lopez** [comment]
Could you filter your logs with the following string?

`adding incremental state for epochs`

Could you share the filtered results here or via Slack?

**Comment by faevourite** [comment]
Ah, unfortunately these logs have rolled over, sorry. Will do the next time I get the error.

**Comment by faevourite** [comment]
Hmm, haven't seen this error in a while. I'll reopen this if I do again.
