### ISSUE TITLE
Moving repository location causes segfault

### ISSUE THREAD

**Issue by mbiebl** [kopia/kopia#559]
Version: 0.6.3

Hi,
I decided to move my repository to a different location (external hard drive). Now `kopia server` segfaults:

```
$ kopia server start --htpasswd-file ./password.txt --tls-cert-file ./repo.cert --tls-key-file ./repo.key --address 0.0.0.0:51515
13:40:31.840 [kopia/repo] failed to open repository: cannot open storage: cannot access storage path: stat /mnt/share/kopia: no such file or directory
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x8e6ed6]

goroutine 1 [running]:
github.com/kopia/kopia/repo.(*DirectRepository).FindManifests(0x0, 0x12e44a0, 0xc0005884e0, 0xc00008fa10, 0x3f, 0x40922b, 0xc0003c8000, 0x103ff00, 0x10c58c0)
	/home/travis/gopath/src/github.com/kopia/kopia/repo/repository.go:109 +0x26
github.com/kopia/kopia/repo/maintenance.manifestIDs(0x12e44a0, 0xc0005884e0, 0x12f4260, 0x0, 0x40a4ba, 0x103ff00, 0x10c58c0, 0xc00012cb01, 0x12f4260)
	/home/travis/gopath/src/github.com/kopia/kopia/repo/maintenance/maintenance_params.go:115 +0x55
github.com/kopia/kopia/repo/maintenance.HasParams(0x12e44a0, 0xc0005884e0, 0x12f4260, 0x0, 0x0, 0x1, 0xc000129b18)
	/home/travis/gopath/src/github.com/kopia/kopia/repo/maintenance/maintenance_params.go:59 +0x4d
github.com/kopia/kopia/cli.maybeAutoUpgradeRepository(0x12e44a0, 0xc0005884e0, 0x12f5c60, 0x0)
	/home/travis/gopath/src/github.com/kopia/kopia/cli/auto_upgrade.go:22 +0xa9
github.com/kopia/kopia/cli.runServer(0x12e44a0, 0xc0005884e0, 0x12f5c60, 0x0, 0x12f5c60, 0x0)
	/home/travis/gopath/src/github.com/kopia/kopia/cli/command_server_start.go:55 +0x29a
github.com/kopia/kopia/cli.maybeRepositoryAction.func1.1(0x0, 0x0)
	/home/travis/gopath/src/github.com/kopia/kopia/cli/app.go:146 +0x14a
github.com/kopia/kopia/cli.withProfiling(...)
	/home/travis/gopath/src/github.com/kopia/kopia/cli/profile_disabled.go:7
github.com/kopia/kopia/cli.maybeRepositoryAction.func1(0xc0003c6bd0, 0x40a613, 0xfb01a0)
	/home/travis/gopath/src/github.com/kopia/kopia/cli/app.go:125 +0x5d
gopkg.in/alecthomas/kingpin%2ev2.(*actionMixin).applyActions(0xc000556fd8, 0xc0003c6bd0, 0x0, 0x0)
	/home/travis/gopath/pkg/mod/gopkg.in/alecthomas/kingpin.v2@v2.2.6/actions.go:28 +0x6d
gopkg.in/alecthomas/kingpin%2ev2.(*Application).applyActions(0xc0000de690, 0xc0003c6bd0, 0x0, 0x0)
	/home/travis/gopath/pkg/mod/gopkg.in/alecthomas/kingpin.v2@v2.2.6/app.go:557 +0xdc
gopkg.in/alecthomas/kingpin%2ev2.(*Application).execute(0xc0000de690, 0xc0003c6bd0, 0xc00056f360, 0x2, 0x2, 0x0, 0x0, 0x0, 0xc0000a3fb8)
	/home/travis/gopath/pkg/mod/gopkg.in/alecthomas/kingpin.v2@v2.2.6/app.go:390 +0x8f
gopkg.in/alecthomas/kingpin%2ev2.(*Application).Parse(0xc0000de690, 0xc0000aa010, 0xa, 0xa, 0x1, 0xc0000a3fc0, 0x0, 0x1)
	/home/travis/gopath/pkg/mod/gopkg.in/alecthomas/kingpin.v2@v2.2.6/app.go:222 +0x1fe
main.main()
	/home/travis/gopath/src/github.com/kopia/kopia/main.go:78 +0x177
```
`/mnt/share/kopia` is the old location.

**Comment by mbiebl** [comment]
After updating the the repository config via `kopia repository connect filesystem --path ...`, the server starts up properly.

**Comment by jkowalski** [comment]
yeah, the panic is unexpected, otherwise you did the right thing by reconnecting. I'll keep the bug to fix the panic.

**Comment by mbiebl** [comment]
Thanks!
