### ISSUE TITLE
kopia mount - fatal error: runtime: out of memory

### ISSUE THREAD

**Issue by wmerlotto** [kopia/kopia#619]
Hi!
In a file restoration process the "kopia mount" was interrupted by a fatal error when trying to copy a 1.3GB file.

```bash
kopia mount kdbd7e7e86c89527db87b3d89c75c4b94 /mnt/ &
rsync  -au --progress /mnt/data/* /srv/data/
```
```go
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x115cc68, 0x16)
	/home/travis/.gimme/versions/go1.15.2.linux.amd64/src/runtime/panic.go:1116 +0x72
runtime.sysMap(0xc0c4000000, 0x80000000, 0x19b84f8)
	/home/travis/.gimme/versions/go1.15.2.linux.amd64/src/runtime/mem_linux.go:169 +0xc6
runtime.(*mheap).sysAlloc(0x199cd60, 0x80000000, 0x42beb7, 0x199cd68)
	/home/travis/.gimme/versions/go1.15.2.linux.amd64/src/runtime/malloc.go:727 +0x1e5
runtime.(*mheap).grow(0x199cd60, 0x40000, 0x0)
	/home/travis/.gimme/versions/go1.15.2.linux.amd64/src/runtime/mheap.go:1344 +0x85
runtime.(*mheap).allocSpan(0x199cd60, 0x40000, 0x7f70bdf00100, 0x19b8508, 0x41661b)
	/home/travis/.gimme/versions/go1.15.2.linux.amd64/src/runtime/mheap.go:1160 +0x6b6
runtime.(*mheap).alloc.func1()
	/home/travis/.gimme/versions/go1.15.2.linux.amd64/src/runtime/mheap.go:907 +0x65
runtime.(*mheap).alloc(0x199cd60, 0x40000, 0xc000180101, 0x42996a)
	/home/travis/.gimme/versions/go1.15.2.linux.amd64/src/runtime/mheap.go:901 +0x85
runtime.largeAlloc(0x7ffffe00, 0x460101, 0xc031186000)
	/home/travis/.gimme/versions/go1.15.2.linux.amd64/src/runtime/malloc.go:1177 +0x92
runtime.mallocgc.func1()
	/home/travis/.gimme/versions/go1.15.2.linux.amd64/src/runtime/malloc.go:1071 +0x46
runtime.systemstack(0x57)
	/home/travis/.gimme/versions/go1.15.2.linux.amd64/src/runtime/asm_amd64.s:370 +0x66
runtime.mstart()
	/home/travis/.gimme/versions/go1.15.2.linux.amd64/src/runtime/proc.go:1116

goroutine 74605 [running]:
runtime.systemstack_switch()
	/home/travis/.gimme/versions/go1.15.2.linux.amd64/src/runtime/asm_amd64.s:330 fp=0xc000c118b8 sp=0xc000c118b0 pc=0x46a3a0
runtime.mallocgc(0x7ffffe00, 0xf7e020, 0xc031186001, 0xc001e29220)
	/home/travis/.gimme/versions/go1.15.2.linux.amd64/src/runtime/malloc.go:1070 +0x938 fp=0xc000c11958 sp=0xc000c118b8 pc=0x40dc98
runtime.makeslice(0xf7e020, 0x7ffffe00, 0x7ffffe00, 0x4fac79)
	/home/travis/.gimme/versions/go1.15.2.linux.amd64/src/runtime/slice.go:98 +0x6c fp=0xc000c11988 sp=0xc000c11958 pc=0x44d2cc
bytes.makeSlice(0x7ffffe00, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.15.2.linux.amd64/src/bytes/buffer.go:229 +0x73 fp=0xc000c119c8 sp=0xc000c11988 pc=0x4ba053
bytes.(*Buffer).grow(0xc000c11ac0, 0x200, 0x20000000)
	/home/travis/.gimme/versions/go1.15.2.linux.amd64/src/bytes/buffer.go:142 +0x156 fp=0xc000c11a18 sp=0xc000c119c8 pc=0x4b9976
bytes.(*Buffer).ReadFrom(0xc000c11ac0, 0x7f70bf65ced8, 0xc001383c40, 0x7f70bf65ced8, 0xc001cbe070, 0xc001a31af8)
	/home/travis/.gimme/versions/go1.15.2.linux.amd64/src/bytes/buffer.go:202 +0x48 fp=0xc000c11a88 sp=0xc000c11a18 pc=0x4b9e28
io/ioutil.readAll(0x7f70bf65ced8, 0xc001383c40, 0x200, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.15.2.linux.amd64/src/io/ioutil/ioutil.go:36 +0xe5 fp=0xc000c11b08 sp=0xc000c11a88 pc=0x5b6085
io/ioutil.ReadAll(...)
	/home/travis/.gimme/versions/go1.15.2.linux.amd64/src/io/ioutil/ioutil.go:45
github.com/kopia/kopia/internal/fusemount.(*fuseFileNode).ReadAll(0xc002906430, 0x12be0c0, 0xc0029cd100, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/kopia/kopia/internal/fusemount/fusefs.go:46 +0x135 fp=0xc000c11b70 sp=0xc000c11b08 pc=0x97a6b5
bazil.org/fuse/fs.(*Server).handleRequest(0xc0004c7980, 0x12be0c0, 0xc0029cd100, 0x12a4a60, 0xc002906430, 0xc002a8fb00, 0x12b8c40, 0xc002324bd0, 0xc000c11eb0, 0xc0004c0000, ...)
	/home/travis/gopath/pkg/mod/bazil.org/fuse@v0.0.0-20200117225306-7b5117fecadc/fs/serve.go:1223 +0x971 fp=0xc000c11dc0 sp=0xc000c11b70 pc=0x974f71
bazil.org/fuse/fs.(*Server).serve(0xc0004c7980, 0x12b8c40, 0xc002324bd0)
	/home/travis/gopath/pkg/mod/bazil.org/fuse@v0.0.0-20200117225306-7b5117fecadc/fs/serve.go:871 +0x409 fp=0xc000c11f88 sp=0xc000c11dc0 pc=0x9740c9
bazil.org/fuse/fs.(*Server).Serve.func1(0xc0004c7980, 0x12b8c40, 0xc002324bd0)
	/home/travis/gopath/pkg/mod/bazil.org/fuse@v0.0.0-20200117225306-7b5117fecadc/fs/serve.go:425 +0x6f fp=0xc000c11fc8 sp=0xc000c11f88 pc=0x978a0f
runtime.goexit()
	/home/travis/.gimme/versions/go1.15.2.linux.amd64/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc000c11fd0 sp=0xc000c11fc8 pc=0x46bfe1
created by bazil.org/fuse/fs.(*Server).Serve
	/home/travis/gopath/pkg/mod/bazil.org/fuse@v0.0.0-20200117225306-7b5117fecadc/fs/serve.go:423 +0x35f

goroutine 1 [select, 1 minutes]:
github.com/kopia/kopia/cli.runMountCommand(0x12be180, 0xc0004d2c30, 0x12cc600, 0xc000374960, 0x12cc600, 0xc000374960)
	/home/travis/gopath/src/github.com/kopia/kopia/cli/command_mount.go:71 +0x616
github.com/kopia/kopia/cli.maybeRepositoryAction.func1.1(0x0, 0x0)
	/home/travis/gopath/src/github.com/kopia/kopia/cli/app.go:146 +0x14a
github.com/kopia/kopia/cli.withProfiling(...)
	/home/travis/gopath/src/github.com/kopia/kopia/cli/profile_disabled.go:7
github.com/kopia/kopia/cli.maybeRepositoryAction.func1(0xc000328c60, 0x40b705, 0xff68c0)
	/home/travis/gopath/src/github.com/kopia/kopia/cli/app.go:125 +0x5d
gopkg.in/alecthomas/kingpin%2ev2.(*actionMixin).applyActions(0xc0004aa258, 0xc000328c60, 0x0, 0x0)
	/home/travis/gopath/pkg/mod/gopkg.in/alecthomas/kingpin.v2@v2.2.6/actions.go:28 +0x6d
gopkg.in/alecthomas/kingpin%2ev2.(*Application).applyActions(0xc0000b6870, 0xc000328c60, 0x0, 0x0)
	/home/travis/gopath/pkg/mod/gopkg.in/alecthomas/kingpin.v2@v2.2.6/app.go:557 +0xdc
gopkg.in/alecthomas/kingpin%2ev2.(*Application).execute(0xc0000b6870, 0xc000328c60, 0xc0004e6040, 0x1, 0x1, 0x0, 0x0, 0x0, 0xc0004da0f8)
	/home/travis/gopath/pkg/mod/gopkg.in/alecthomas/kingpin.v2@v2.2.6/app.go:390 +0x90
gopkg.in/alecthomas/kingpin%2ev2.(*Application).Parse(0xc0000b6870, 0xc000030090, 0x3, 0x3, 0x1, 0xc0004da100, 0x0, 0x1)
	/home/travis/gopath/pkg/mod/gopkg.in/alecthomas/kingpin.v2@v2.2.6/app.go:222 +0x213
main.main()
	/home/travis/gopath/src/github.com/kopia/kopia/main.go:77 +0x17b

goroutine 6 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc00007a3c0)
	/home/travis/gopath/pkg/mod/go.opencensus.io@v0.22.3/stats/view/worker.go:154 +0x105
created by go.opencensus.io/stats/view.init.0
	/home/travis/gopath/pkg/mod/go.opencensus.io@v0.22.3/stats/view/worker.go:32 +0x57

goroutine 9 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x1983440)
	/home/travis/gopath/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:882 +0x8b
created by github.com/golang/glog.init.0
	/home/travis/gopath/pkg/mod/github.com/golang/glog@v0.0.0-20160126235308-23def4e6c14b/glog.go:410 +0x274

goroutine 23 [chan receive, 1 minutes]:
github.com/kopia/kopia/cli.onCtrlC.func1(0xc000475da0, 0xc0004e6890)
	/home/travis/gopath/src/github.com/kopia/kopia/cli/config.go:44 +0x34
created by github.com/kopia/kopia/cli.onCtrlC
	/home/travis/gopath/src/github.com/kopia/kopia/cli/config.go:43 +0xb5

goroutine 19 [IO wait]:
internal/poll.runtime_pollWait(0x7f70bfa898d8, 0x72, 0x12a7a80)
	/home/travis/.gimme/versions/go1.15.2.linux.amd64/src/runtime/netpoll.go:220 +0x55
internal/poll.(*pollDesc).wait(0xc0004ec398, 0x72, 0xc000568000, 0x1069e, 0x1069e)
	/home/travis/.gimme/versions/go1.15.2.linux.amd64/src/internal/poll/fd_poll_runtime.go:87 +0x45
internal/poll.(*pollDesc).waitRead(...)
	/home/travis/.gimme/versions/go1.15.2.linux.amd64/src/internal/poll/fd_poll_runtime.go:92
internal/poll.(*FD).Read(0xc0004ec380, 0xc000568000, 0x1069e, 0x1069e, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.15.2.linux.amd64/src/internal/poll/fd_unix.go:159 +0x1b1
net.(*netFD).Read(0xc0004ec380, 0xc000568000, 0x1069e, 0x1069e, 0x203000, 0x6da05b, 0xc0004c0160)
	/home/travis/.gimme/versions/go1.15.2.linux.amd64/src/net/fd_posix.go:55 +0x4f
net.(*conn).Read(0xc00018e068, 0xc000568000, 0x1069e, 0x1069e, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.15.2.linux.amd64/src/net/net.go:182 +0x8e
crypto/tls.(*atLeastReader).Read(0xc001e29200, 0xc000568000, 0x1069e, 0x1069e, 0x1a, 0x10699, 0xc000085730)
	/home/travis/.gimme/versions/go1.15.2.linux.amd64/src/crypto/tls/conn.go:779 +0x62
bytes.(*Buffer).ReadFrom(0xc0004c0280, 0x12a36e0, 0xc001e29200, 0x40b3e5, 0xfeff40, 0x1109540)
	/home/travis/.gimme/versions/go1.15.2.linux.amd64/src/bytes/buffer.go:204 +0xb1
crypto/tls.(*Conn).readFromUntil(0xc0004c0000, 0x12a6020, 0xc00018e068, 0x5, 0xc00018e068, 0x9)
	/home/travis/.gimme/versions/go1.15.2.linux.amd64/src/crypto/tls/conn.go:801 +0xf3
crypto/tls.(*Conn).readRecordOrCCS(0xc0004c0000, 0x0, 0x0, 0xc000085d38)
	/home/travis/.gimme/versions/go1.15.2.linux.amd64/src/crypto/tls/conn.go:608 +0x115
crypto/tls.(*Conn).readRecord(...)
	/home/travis/.gimme/versions/go1.15.2.linux.amd64/src/crypto/tls/conn.go:576
crypto/tls.(*Conn).Read(0xc0004c0000, 0xc000157000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.15.2.linux.amd64/src/crypto/tls/conn.go:1252 +0x15f
bufio.(*Reader).Read(0xc000475b60, 0xc0003a01f8, 0x9, 0x9, 0xc000085d38, 0x11a2800, 0x792c0b)
	/home/travis/.gimme/versions/go1.15.2.linux.amd64/src/bufio/bufio.go:227 +0x222
io.ReadAtLeast(0x12a3440, 0xc000475b60, 0xc0003a01f8, 0x9, 0x9, 0x9, 0xc000040050, 0x0, 0x12a38a0)
	/home/travis/.gimme/versions/go1.15.2.linux.amd64/src/io/io.go:314 +0x87
io.ReadFull(...)
	/home/travis/.gimme/versions/go1.15.2.linux.amd64/src/io/io.go:333
net/http.http2readFrameHeader(0xc0003a01f8, 0x9, 0x9, 0x12a3440, 0xc000475b60, 0x0, 0x0, 0xc003198bd0, 0x0)
	/home/travis/.gimme/versions/go1.15.2.linux.amd64/src/net/http/h2_bundle.go:1477 +0x89
net/http.(*http2Framer).ReadFrame(0xc0003a01c0, 0xc003198bd0, 0x0, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.15.2.linux.amd64/src/net/http/h2_bundle.go:1735 +0xa5
net/http.(*http2clientConnReadLoop).run(0xc000085fa8, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.15.2.linux.amd64/src/net/http/h2_bundle.go:8240 +0x8d
net/http.(*http2ClientConn).readLoop(0xc0003ec600)
	/home/travis/.gimme/versions/go1.15.2.linux.amd64/src/net/http/h2_bundle.go:8168 +0x6f
created by net/http.(*http2Transport).newClientConn
	/home/travis/.gimme/versions/go1.15.2.linux.amd64/src/net/http/h2_bundle.go:7173 +0x66e

goroutine 22 [syscall, 1 minutes]:
os/signal.signal_recv(0x0)
	/home/travis/.gimme/versions/go1.15.2.linux.amd64/src/runtime/sigqueue.go:147 +0x9d
os/signal.loop()
	/home/travis/.gimme/versions/go1.15.2.linux.amd64/src/os/signal/signal_unix.go:23 +0x25
created by os/signal.Notify.func1.1
	/home/travis/.gimme/versions/go1.15.2.linux.amd64/src/os/signal/signal.go:150 +0x45

goroutine 33 [select]:
github.com/kopia/kopia/internal/buf.NewPool.func1(0xc000150300, 0x12be180, 0xc0004d2c30)
	/home/travis/gopath/src/github.com/kopia/kopia/internal/buf/pool.go:145 +0xfa
created by github.com/kopia/kopia/internal/buf.NewPool
	/home/travis/gopath/src/github.com/kopia/kopia/internal/buf/pool.go:143 +0x185

goroutine 20 [syscall]:
syscall.Syscall(0x0, 0xc, 0xc002ae8000, 0x21000, 0x101dd20, 0xc000ce2690, 0x101dd20)
	/home/travis/.gimme/versions/go1.15.2.linux.amd64/src/syscall/asm_linux_amd64.s:18 +0x5
syscall.read(0xc, 0xc002ae8000, 0x21000, 0x21000, 0x50, 0x0, 0x0)
	/home/travis/.gimme/versions/go1.15.2.linux.amd64/src/syscall/zsyscall_linux_amd64.go:686 +0x5a
syscall.Read(...)
	/home/travis/.gimme/versions/go1.15.2.linux.amd64/src/syscall/syscall_unix.go:187
bazil.org/fuse.(*Conn).ReadRequest(0xc000188c60, 0x119f698, 0xc0004c7980, 0x12b8c40, 0xc002324bd0)
	/home/travis/gopath/pkg/mod/bazil.org/fuse@v0.0.0-20200117225306-7b5117fecadc/fuse.go:578 +0xe5
bazil.org/fuse/fs.(*Server).Serve(0xc0004c7980, 0x12a4ae0, 0xc00001f8e0, 0x0, 0x0)
	/home/travis/gopath/pkg/mod/bazil.org/fuse@v0.0.0-20200117225306-7b5117fecadc/fs/serve.go:414 +0x373
bazil.org/fuse/fs.Serve(0xc000188c60, 0x12a4ae0, 0xc00001f8e0, 0x1, 0xc000378290)
	/home/travis/gopath/pkg/mod/bazil.org/fuse@v0.0.0-20200117225306-7b5117fecadc/fs/serve.go:435 +0xba
github.com/kopia/kopia/internal/mount.Directory.func1(0xc000475d40, 0xc000188c60, 0x12a4a40, 0xc00001f870, 0xc0001c0180)
	/home/travis/gopath/src/github.com/kopia/kopia/internal/mount/mount_fuse.go:58 +0x6f
created by github.com/kopia/kopia/internal/mount.Directory
	/home/travis/gopath/src/github.com/kopia/kopia/internal/mount/mount_fuse.go:57 +0x285
```

I tried with kopia 0.6.4 and 0.7.0-rc1 (error above).
The installation are client/server and mount was issued on client machine, which have 6GB RAM + swap.

**Comment by julio-lopez** [comment]
#620

**Comment by jkowalski** [comment]
This is closed now.
