### ISSUE TITLE
0.7.0-rc: Alignment issue on ARM

### ISSUE THREAD

**Issue by aksdb** [kopia/kopia#631]
Snapshotting on ARM leads to:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x11b20]
goroutine 40 [running]:
runtime/internal/atomic.goXadd64(0x2f27bc4, 0x77, 0x0, 0xc192d8, 0x2dc1fb0)
        /home/travis/.gimme/versions/go1.15.2.linux.amd64/src/runtime/internal/atomic/atomic_arm.go:103 +0x1c
github.com/kopia/kopia/snapshot/snapshotfs.(*Uploader).processNonDirectories.func1(0xc154b8, 0x30820e0, 0xc19248, 0x2e6fbf0, 0x2f4cca0, 0x20, 0x0, 0x0)
        /home/travis/gopath/src/github.com/kopia/kopia/snapshot/snapshotfs/upload.go:700 +0x408
github.com/kopia/kopia/snapshot/snapshotfs.(*Uploader).foreachEntryUnlessCanceled.func2(0x0, 0x3087f90)
        /home/travis/gopath/src/github.com/kopia/kopia/snapshot/snapshotfs/upload.go:428 +0x150
golang.org/x/sync/errgroup.(*Group).Go.func1(0x30a9dd0, 0x3082140)
        /home/travis/gopath/pkg/mod/golang.org/x/sync@v0.0.0-20200317015054-43a5402ce75a/errgroup/errgroup.go:57 +0x50
created by golang.org/x/sync/errgroup.(*Group).Go
        /home/travis/gopath/pkg/mod/golang.org/x/sync@v0.0.0-20200317015054-43a5402ce75a/errgroup/errgroup.go:54 +0x50
```

The alignment check is done against the whole address; not relative to the current data structure.
Since `snapshot.Stats` is embedded into `snapshotfs.Uploader`, the alignment is no longer a multiple of ptrsize.

This change fixes it:
```patch
diff --git a/snapshot/snapshotfs/upload.go b/snapshot/snapshotfs/upload.go
index b84a353b..bed20891 100644
--- a/snapshot/snapshotfs/upload.go
+++ b/snapshot/snapshotfs/upload.go
@@ -47,6 +47,7 @@ const (
 type Uploader struct {
        // values aligned to 8-bytes due to atomic access
        totalWrittenBytes int64
+       stats             snapshot.Stats
 
        Progress UploadProgress
 
@@ -69,7 +70,6 @@ type Uploader struct {
 
        repo repo.Repository
 
-       stats    snapshot.Stats
        canceled int32
 
        uploadBufPool sync.Pool
```

It looks like the added bool `IgnoreReadErrors` might be at fault; but this one is dated to February, so it's weird that it worked in between (unless I just miss a merge somewhere). It's also weird that static analysis doesn't catch it and that apparently the integration tests work. Very weird. But in any case, moving that one line fixes it for me.

**Comment by jkowalski** [comment]
we only run integration tests on arm64 (not armhf) which for some reason does not fail. I wish we had armhf CI support.

I'll send a fix shortly.
