### ISSUE TITLE
[Robustness] Panic in long-running robustness job

### ISSUE THREAD

**Issue by julio-lopez** [kopia/kopia#746]
Observed in a couple of tests in a long running robustness job.
* `TestOneLargeFile`
* `TestRandomizedSmall`

Storage backend: S3
Kopia version: e03971fc

```
...
Processed 58195 (19 GB) of 93354 (35.8 GB) 617 Mbit/s (53.0%) remaining 3m38s.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8eafb5]

goroutine 51 [running]:
github.com/kopia/kopia/repo/object.(*objectReader).openCurrentChunk(0xc0027a4070, 0x0, 0x0)
	/var/lib/shippable/d189bfca-b0f3-4bc5-a45c-aebbdddb854d/build/IN/kopia_repo/gitRepo/repo/object/object_reader.go:87 +0xd5
github.com/kopia/kopia/repo/object.(*objectReader).Read(0xc0027a4070, 0xc000574000, 0x8000, 0x8000, 0x1017e40, 0x7f382f21e501, 0xc000574000)
	/var/lib/shippable/d189bfca-b0f3-4bc5-a45c-aebbdddb854d/build/IN/kopia_repo/gitRepo/repo/object/object_reader.go:63 +0x16f
io.copyBuffer(0x136bca0, 0xc003be2190, 0x7f37e47856e0, 0xc000eb0320, 0xc000574000, 0x8000, 0x8000, 0x4ad205, 0xc0018ca2d0, 0x4aa4b9)
	/usr/local/go/src/io/io.go:409 +0x12c
io.Copy(...)
	/usr/local/go/src/io/io.go:368
os.genericReadFrom(0xc0020d4028, 0x7f37e47856e0, 0xc000eb0320, 0x0, 0x0, 0x0)
	/usr/local/go/src/os/file.go:159 +0x99
os.(*File).ReadFrom(0xc0020d4028, 0x7f37e47856e0, 0xc000eb0320, 0x7f37e4785720, 0xc0020d4028, 0x1)
	/usr/local/go/src/os/file.go:153 +0x217
io.copyBuffer(0x136a6c0, 0xc0020d4028, 0x7f37e47856e0, 0xc000eb0320, 0x0, 0x0, 0x0, 0xc0000b0200, 0x5, 0x11fd49a)
	/usr/local/go/src/io/io.go:395 +0x2ff
io.Copy(...)
	/usr/local/go/src/io/io.go:368
github.com/natefinch/atomic.WriteFile(0xc0008fe380, 0x7e, 0x7f37e47856e0, 0xc000eb0320, 0x0, 0x0)
	/go/pkg/mod/github.com/natefinch/atomic@v0.0.0-20200526193002-18c0533a5b09/atomic.go:39 +0x225
github.com/kopia/kopia/snapshot/restore.(*FilesystemOutput).copyFileContent(0xc00010e760, 0x13838a0, 0xc0000c6cc0, 0xc0008fe380, 0x7e, 0x1390940, 0xc002baca40, 0x0, 0x0)
	/var/lib/shippable/d189bfca-b0f3-4bc5-a45c-aebbdddb854d/build/IN/kopia_repo/gitRepo/snapshot/restore/local_fs_output.go:246 +0x269
github.com/kopia/kopia/snapshot/restore.(*FilesystemOutput).WriteFile(0xc00010e760, 0x13838a0, 0xc0000c6cc0, 0xc00262c0a0, 0x15, 0x1390940, 0xc002baca40, 0xe, 0xc002bb06a8)
	/var/lib/shippable/d189bfca-b0f3-4bc5-a45c-aebbdddb854d/build/IN/kopia_repo/gitRepo/snapshot/restore/local_fs_output.go:82 +0x31e
github.com/kopia/kopia/snapshot/restore.(*copier).copyEntry(0xc0004f0580, 0x13838a0, 0xc0000c6cc0, 0x138f900, 0xc002baca40, 0xc00262c0a0, 0x15, 0xc002bacbc0, 0x1a68f20, 0xbff0ec7c552f9bd3)
	/var/lib/shippable/d189bfca-b0f3-4bc5-a45c-aebbdddb854d/build/IN/kopia_repo/gitRepo/snapshot/restore/restore.go:110 +0x4a4
github.com/kopia/kopia/snapshot/restore.(*copier).copyDirectoryContent.func2(0xc000114e10, 0x13837e0)
	/var/lib/shippable/d189bfca-b0f3-4bc5-a45c-aebbdddb854d/build/IN/kopia_repo/gitRepo/snapshot/restore/restore.go:178 +0x14c
github.com/kopia/kopia/internal/parallelwork.(*Queue).Process.func1(0x0, 0x0)
	/var/lib/shippable/d189bfca-b0f3-4bc5-a45c-aebbdddb854d/build/IN/kopia_repo/gitRepo/internal/parallelwork/parallel_work_queue.go:79 +0x99
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc000525080, 0xc00010f880)
	/go/pkg/mod/golang.org/x/sync@v0.0.0-20200625203802-6e8e738ad208/errgroup/errgroup.go:57 +0x59
created by golang.org/x/sync/errgroup.(*Group).Go
	/go/pkg/mod/golang.org/x/sync@v0.0.0-20200625203802-6e8e738ad208/errgroup/errgroup.go:54 +0x66
2020/12/23 12:39:16 
2020/12/23 12:39:16 error="exit status 2"
    robustness_test.go:57: err: exit status 2
--- FAIL: TestOneLargeFile (390.85s)
```

**Comment by julio-lopez** [comment]
Fixed in #747
